/* ============================================================
   tanren-bank.js
   各Lecciónの「鍛錬」タブの問題データ。
   レッスンページ（鍛錬タブの表示）と review.html（復習）の両方から読み込む。

   書き方：
     TANREN_SOURCE[課番号] = [ { num, title, items: [ [問題文, 和訳, 解説], ... ] }, ... ]
     問題文の [[答え|ヒント]] が穴埋めになる（ヒントは省略可）。
     問題のIDは「L課-tr-通し番号」。既存の問題の順番を入れ替えると
     復習の記録とずれるため、問題を追加するときは各課の末尾（最後のグループの後ろ）に足す。
   ============================================================ */

const TANREN_SOURCE = {};

TANREN_SOURCE[2] = [
  { num: '①', title: '名詞の性と数・冠詞', items: [
    ['Hoy es [[un|día の性に注意]] día muy bonito.',
     '今日はとてもいい日だ。',
     '<b>un</b>：día は語尾が -a だが<b>男性名詞</b>の例外。不定冠詞は男性単数の un。'],
    ['[[El|-ma で終わる名詞]] problema es muy difícil.',
     'その問題はとても難しい。',
     '<b>El</b>：語尾が -ma の名詞は多くが男性名詞（problema, idioma など）。'],
    ['[[La|mano の性に注意]] mano de mi hijo es muy [[pequeña|pequeño を一致させる]].',
     '私の息子の手はとても小さい。',
     '<b>La</b>：mano は語尾が -o だが<b>女性名詞</b>の例外。<b>pequeña</b>：形容詞も女性形にそろえる。'],
    ['Hay [[unas|不定冠詞・複数]] fotos de mi familia en la mesa.',
     'テーブルの上に家族の写真が何枚かある。',
     '<b>unas</b>：foto は fotografía の省略形なので<b>女性名詞</b>。女性複数の不定冠詞は unas。'],
    ['[[El|agua の冠詞に注意]] agua del río está muy [[fría|frío を一致させる]].',
     'その川の水はとても冷たい。',
     '<b>El</b>：agua は女性名詞だが、アクセントのある a- で始まるため単数では el を使う。<b>fría</b>：名詞自体は女性なので、形容詞は女性形。'],
    ['En la mesa hay tres [[lápices|lápiz の複数形]].',
     'テーブルの上に鉛筆が3本ある。',
     '<b>lápices</b>：-z で終わる名詞は z を c に変えて -es を付ける（lápiz → lápices）。'],
    ['En mi ciudad hay dos [[estaciones|estación の複数形]].',
     '私の町には駅が2つある。',
     '<b>estaciones</b>：子音で終わるので +es。複数形では強勢の位置が規則どおりになるため、アクセント記号が消える（estación → estaciones）。'],
    ['Hay dos [[paraguas|paraguas の複数形]] en la entrada.',
     '入口に傘が2本ある。',
     '<b>paraguas</b>：単数と複数で形が変わらない「単複同形の名詞」。数は冠詞や数詞で判断する。'],
    ['Es el coche [[del|de ＋ el]] padre de Ana.',
     'それはアナのお父さんの車だ。',
     '<b>del</b>：前置詞 de と定冠詞 el が続くと必ず縮約して del になる。'],
    ['Voy [[al|a ＋ el]] cine con [[la|hermana は女性名詞]] hermana de Pedro.',
     '私はペドロの姉（妹）と映画館へ行く。',
     '<b>al</b>：a ＋ el は縮約して al。<b>la</b>：hermana は女性名詞なので la。'],
    ['El libro es [[de él|前置詞 de ＋ 代名詞「彼」]], no [[del|前置詞 de ＋ 定冠詞 el]] profesor.',
     'その本は彼のもので、先生のものではない。',
     '<b>de él</b>：主語代名詞 él（アクセント記号あり）とは縮約しない。<b>del</b>：定冠詞 el（アクセント記号なし）とは縮約する。'],
    ['[[La|-ión で終わる名詞]] lección de hoy es muy interesante.',
     '今日の課はとても面白い。',
     '<b>La</b>：語尾が -ión の名詞は女性名詞（lección, nación など）。'],
    ['Tu padre es [[una|persona の性に注意]] persona muy [[simpática|simpático を一致させる]].',
     '君のお父さんはとても感じのいい人だ。',
     '<b>una</b>：persona は指す相手が男性でも<b>女性名詞</b>。<b>simpática</b>：形容詞も persona に合わせて女性形。'],
    ['[[El|-pa で終わる名詞]] mapa de España está sobre la mesa.',
     'スペインの地図はテーブルの上にある。',
     '<b>El</b>：mapa は語尾が -a だが<b>男性名詞</b>の例外。'],
    ['[[La|女性の学生]] estudiante mexicana está en [[la|clase の性]] clase de español.',
     'そのメキシコ人の女子学生はスペイン語の授業に出ている。',
     '<b>La</b>：estudiante は「男女同形の名詞」。女性を指すときは la estudiante（形容詞も mexicana）。<b>la</b>：clase は語尾 -e だが女性名詞。'],
  ]},

  { num: '②', title: '主語人称代名詞・ser と estar', items: [
    ['Nosotros [[somos|ser・nosotros]] de Osaka, pero ahora [[estamos|estar・nosotros]] en Madrid.',
     '私たちは大阪出身だが、今はマドリードにいる。',
     '<b>somos</b>：出身は ser（ser de＋場所）。<b>estamos</b>：今いる場所（所在）は estar。'],
    ['¿[[Eres|ser・tú]] tú estudiante? — Sí, [[soy|ser・yo]] estudiante de español.',
     '君は学生？ — うん、スペイン語の学生だよ。',
     '<b>Eres / soy</b>：身分・職業は ser。tú → eres、yo → soy。'],
    ['Mi padre [[es|職業]] médico y ahora [[está|所在]] en el hospital.',
     '私の父は医者で、今は病院にいる。',
     '<b>es</b>：職業（名詞）は ser。「estar＋名詞」という形はない。<b>está</b>：人の所在は estar。'],
    ['¿Cómo [[están|estar・ustedes]] ustedes? — [[Estamos|estar・nosotros]] muy bien, gracias.',
     '皆さんお元気ですか？ — とても元気です、ありがとう。',
     '<b>están</b>：ustedes は文法上3人称複数なので están。<b>Estamos</b>：体調・調子は estar。'],
    ['La fiesta [[es|イベントの開催場所]] en casa de Ana, pero Ana todavía [[está|人の所在]] en la universidad.',
     'パーティーはアナの家で開かれるが、アナはまだ大学にいる。',
     '<b>es</b>：イベントが「行われる」場所は ser。<b>está</b>：人や物が「いる・ある」場所は estar。'],
    ['[[Son|時刻（3時）]] las tres y media.',
     '3時半だ。',
     '<b>Son</b>：時刻は ser。2時以降は las（複数）に合わせて son を使う。'],
    ['[[Es|時刻（1時）]] la una de la tarde.',
     '午後1時だ。',
     '<b>Es</b>：1時だけは la una（単数）なので es を使う。'],
    ['La mesa [[es|素材]] de madera y [[está|所在]] en la cocina.',
     'そのテーブルは木製で、台所にある。',
     '<b>es</b>：素材（ser de＋素材）は ser。<b>está</b>：物の所在は、動かない物でも estar。'],
    ['Pedro [[es|性格]] nervioso, pero hoy [[está|今日の状態]] muy tranquilo.',
     'ペドロは神経質な性格だが、今日はとても落ち着いている。',
     '<b>es</b>：生まれつきの性格は ser。<b>está</b>：「今日は」という一時的な状態は estar。'],
    ['Ana, [[estás|今日に限った様子]] muy guapa hoy.',
     'アナ、今日はとてもきれいだね。',
     '<b>estás</b>：「今日は（いつもと違って）」という一時的な評価は estar。Ana es guapa.（ser）なら「アナは美人だ（性質）」。'],
    ['La puerta [[está|状態]] abierta, pero las ventanas [[están|状態・複数]] cerradas.',
     'ドアは開いているが、窓は閉まっている。',
     '<b>está / están</b>：開いている・閉まっているは状態なので estar。主語の数（la puerta / las ventanas）に合わせる。'],
    ['Madrid [[es|首都（補語）]] la capital de España y [[está|所在]] en el centro del país.',
     'マドリードはスペインの首都で、国の中央にある。',
     '<b>es</b>：「〜は…である」と名詞でイコールを表すときは ser。<b>está</b>：地名の所在も estar。'],
    ['Mi hermano [[está|体調]] enfermo y [[está|所在]] en casa.',
     '私の兄（弟）は病気で、家にいる。',
     '<b>está</b>：体調（病気）も所在も estar。'],
    ['Señora López, ¿[[es|usted の活用]] usted de México?',
     'ロペスさん、あなたはメキシコ出身ですか？',
     '<b>es</b>：usted は「あなた」という意味だが、文法上は<b>3人称単数</b>扱い。'],
    ['Ustedes [[son|ustedes の活用]] profesores, ¿verdad?',
     'あなた方は先生ですよね？',
     '<b>son</b>：ustedes は文法上<b>3人称複数</b>扱い。'],
    ['[[Nosotras|私たち（女性のみ）]] somos hermanas.',
     '私たちは姉妹だ。',
     '<b>Nosotras</b>：全員が女性なら nosotras。男性が1人でも含まれれば nosotros。'],
    ['—¿Quién es Juan? —[[Él|彼]] es el hermano de María.',
     'フアンって誰？ — マリアの兄（弟）だよ。',
     '<b>Él</b>：「彼」はアクセント記号付きの él。定冠詞 el と区別する。'],
    ['El libro [[es|所有]] de Ana, pero ahora [[está|所在]] en mi casa.',
     'その本はアナのものだが、今は私の家にある。',
     '<b>es</b>：所有（ser de＋人）は ser。<b>está</b>：今ある場所は estar。'],
    ['¿Dónde [[está|所在]] la estación? — [[Está|所在]] cerca de aquí.',
     '駅はどこにありますか？ — この近くにあります。',
     '<b>está</b>：特定の建物（la estación）の場所を尋ねる・答えるときは estar。'],
    ['Vosotros [[sois|ser・vosotros]] japoneses y [[estáis|estar・vosotros]] en España de vacaciones.',
     '君たちは日本人で、休暇でスペインに来ている。',
     '<b>sois</b>：国籍は ser。<b>estáis</b>：今いる場所は estar。どちらも vosotros の形（スペインで使う）。'],
  ]},

  { num: '③', title: 'さまざまな前置詞', items: [
    ['Un café [[sin|〜なしの]] azúcar y un té [[con|〜入りの]] leche, por favor.',
     '砂糖なしのコーヒーとミルクティーをください。',
     '<b>sin</b>：「〜なしで」。<b>con</b>：「〜と一緒に・〜入りの」。'],
    ['Estudio [[para|目的]] el examen de mañana.',
     '明日の試験のために勉強している。',
     '<b>para</b>：目的（〜に向けて）。por は原因・理由なので使わない。'],
    ['Gracias [[por|理由]] el regalo.',
     'プレゼントをありがとう。',
     '<b>por</b>：感謝の理由を表す。Gracias por ～ は決まった形。'],
    ['¿Vienes [[conmigo|con ＋ mí]] al cine? — No, voy [[con|〜と一緒に]] Juan.',
     '私と一緒に映画に行く？ — ううん、フアンと行くんだ。',
     '<b>conmigo</b>：con ＋ mí は特別な形 conmigo になる。<b>con</b>：3人称や名前の前ではそのまま con。'],
    ['Mañana estoy [[contigo|con ＋ ti]] todo el día.',
     '明日は一日中君と一緒にいるよ。',
     '<b>contigo</b>：con ＋ ti は特別な形 contigo になる。'],
    ['Es un libro [[sobre|〜について]] la historia de México.',
     'それはメキシコの歴史についての本だ。',
     '<b>sobre</b>：「〜の上に」のほか、「〜について」という意味もある。'],
    ['La biblioteca está abierta [[desde|起点]] las nueve [[hasta|終点]] las ocho.',
     '図書館は9時から8時まで開いている。',
     '<b>desde</b>：時間の起点「〜から」。<b>hasta</b>：終点「〜まで」。セットでよく使う。'],
    ['Estoy en Japón [[desde|起点]] abril.',
     '私は4月から日本にいる。',
     '<b>desde</b>：「（ある時点）から今まで」の起点を表す。'],
    ['Soy [[de|出身]] Kioto, pero vivo [[en|場所]] Osaka.',
     '私は京都出身だが、大阪に住んでいる。',
     '<b>de</b>：出身「〜の出身」。<b>en</b>：住んでいる場所「〜に」。'],
    ['Voy [[a|方向]] la universidad [[en|乗り物]] tren.',
     '私は電車で大学へ行く。',
     '<b>a</b>：行き先「〜へ」。<b>en</b>：乗り物で移動するときは en（en tren, en autobús）。'],
    ['El tren va [[de|出発点]] Madrid [[a|到着点]] Barcelona.',
     'その電車はマドリードからバルセロナへ行く。',
     '<b>de … a …</b>：「〜から…へ」。移動の出発点と到着点をセットで表す。'],
    ['Hoy no hay clase [[por|原因]] la lluvia.',
     '雨のせいで今日は授業がない。',
     '<b>por</b>：原因・理由「〜のせいで」。目的の para とは使い分ける。'],
    ['Esta tarde voy [[al|a ＋ el]] museo y después [[a|方向]] la casa [[de|所有]] Carmen.',
     '今日の午後は美術館へ行き、そのあとカルメンの家へ行く。',
     '<b>al</b>：a ＋ el museo → al museo。<b>a</b>：la casa は女性名詞なので縮約しない。<b>de</b>：所有「〜の」。'],
  ]},

  { num: '④', title: '形容詞と性数変化', items: [
    ['Mis padres son [[japoneses|japonés の男性複数]] y mi abuela es [[española|español の女性形]].',
     '私の両親は日本人で、祖母はスペイン人だ。',
     '<b>japoneses</b>：japonés ＋ es。複数ではアクセント記号が消える。<b>española</b>：子音で終わる国籍形容詞は女性形で ＋a。'],
    ['Laura es [[alemana|alemán の女性形]] y sus hermanos también son [[alemanes|alemán の男性複数]].',
     'ラウラはドイツ人で、彼女の兄弟たちもドイツ人だ。',
     '<b>alemana / alemanes</b>：alemán に -a / -es を付けると、アクセント記号が消える。'],
    ['Las chicas [[inglesas|inglés の女性複数]] son muy [[simpáticas|simpático を一致させる]].',
     'そのイギリス人の女の子たちはとても感じがいい。',
     '<b>inglesas</b>：inglés → inglesa → inglesas。<b>simpáticas</b>：女性複数に一致。'],
    ['Es una ciudad [[grande|名詞の後ろ]] y muy [[bonita|bonito を一致させる]].',
     'そこは大きくてとてもきれいな都市だ。',
     '<b>grande</b>：-e で終わる形容詞は性変化しない。名詞の後ろなので短縮もしない。<b>bonita</b>：ciudad（女性）に一致。'],
    ['Carlos es un [[buen|bueno：男性単数名詞の前]] amigo y Marta es una [[buena|bueno：女性単数名詞の前]] amiga.',
     'カルロスはいい友人で、マルタもいい友人だ。',
     '<b>buen</b>：男性単数名詞の直前では bueno → buen。<b>buena</b>：女性名詞の前では短縮しない。'],
    ['Hoy es un [[mal|malo：男性単数名詞の前]] día para ir a la playa.',
     '今日は海に行くには悪い日だ。',
     '<b>mal</b>：男性単数名詞（día）の直前では malo → mal。'],
    ['Picasso es un [[gran|grande：単数名詞の前]] pintor.',
     'ピカソは偉大な画家だ。',
     '<b>gran</b>：単数名詞の直前では grande → gran になり、「偉大な」という意味になる。'],
    ['Buenos Aires es una [[gran|grande：女性単数名詞の前]] ciudad.',
     'ブエノスアイレスはすばらしい都市だ。',
     '<b>gran</b>：grande は男性・女性どちらの<b>単数名詞</b>の前でも gran になる（buen・mal は男性単数の前だけ）。複数の前では grandes。'],
    ['Mis hermanos son [[trabajadores|trabajador の男性複数]], pero mi hermana es un poco [[holgazana|holgazán の女性形]].',
     '私の兄弟たちは勤勉だが、妹は少し怠け者だ。',
     '<b>trabajadores</b>：-dor で終わる形容詞の男性複数は ＋es。<b>holgazana</b>：-án で終わる形容詞の女性形は -ana（アクセント記号は消える）。'],
    ['Los estudiantes son [[jóvenes|joven の複数形]] e [[inteligentes|inteligente の複数形]].',
     '学生たちは若くて頭がいい。',
     '<b>jóvenes</b>：joven ＋ es。強勢の位置を保つため、複数形では<b>アクセント記号が付く</b>。<b>inteligentes</b>：-e で終わるので ＋s。※ i- で始まる語の前では y が e になる。'],
    ['Los coches [[azules|azul の複数形]] son muy [[caros|caro を一致させる]].',
     'その青い車（複数）はとても高い。',
     '<b>azules</b>：子音で終わる形容詞は性変化せず、複数で ＋es。<b>caros</b>：男性複数に一致。'],
    ['Hay [[muchos|数量を表す形容詞]] estudiantes [[chinos|chino を一致させる]] en mi universidad.',
     '私の大学には中国人の学生がたくさんいる。',
     '<b>muchos</b>：数量を表す形容詞は名詞の前に置き、性数一致する。<b>chinos</b>：国籍形容詞は名詞の後ろ。'],
    ['Hoy es el [[primer|primero：男性単数名詞の前]] día de clase.',
     '今日は授業の初日だ。',
     '<b>primer</b>：序数 primero も、bueno と同じく男性単数名詞の直前で -o が落ちる（el primer día / la primera clase）。'],
    ['Hay [[pocas|数量を表す形容詞]] personas en la calle.',
     '通りには人が少ない。',
     '<b>pocas</b>：persona は女性名詞なので poco → pocas（女性複数）。'],
    ['Las casas de la calle son [[viejas|viejo を一致させる]] pero muy [[bonitas|bonito を一致させる]].',
     'その通りの家々は古いが、とてもきれいだ。',
     '<b>viejas / bonitas</b>：主語 las casas（女性複数）に一致させる。ser の後ろの形容詞も性数一致する。'],
  ]},

  { num: '⑤', title: '所有形容詞・haber（hay）', items: [
    ['[[Mis|私の（複数）]] hermanos están en Barcelona y [[mi|私の（単数）]] hermana está en Tokio.',
     '私の兄弟たちはバルセロナに、姉（妹）は東京にいる。',
     '<b>Mis / mi</b>：mi は性変化せず、名詞の数だけに合わせる。'],
    ['[[Nuestros|私たちの（男性複数）]] padres son de Chile.',
     '私たちの両親はチリ出身だ。',
     '<b>Nuestros</b>：nuestro は被所有物（padres：男性複数）の性数に一致する。'],
    ['¿Es [[vuestra|君たちの（女性単数）]] casa? — Sí, es [[nuestra|私たちの（女性単数）]] casa.',
     'これは君たちの家？ — うん、私たちの家だよ。',
     '<b>vuestra / nuestra</b>：vuestro・nuestro は被所有物 casa（女性単数）に一致する。所有者の性ではない。'],
    ['Señor García, ¿es [[su|usted の所有形容詞]] coche?',
     'ガルシアさん、これはあなたの車ですか？',
     '<b>su</b>：usted（あなた）の所有形容詞は su。彼・彼女・彼らと同じ形。'],
    ['Ana y su hermano están con [[sus|彼らの（複数）]] padres.',
     'アナと弟は両親と一緒にいる。',
     '<b>sus</b>：被所有物 padres が複数なので su → sus。'],
    ['—¿De quién es la maleta? —Es [[mía|私の（後置形）]].',
     'そのスーツケースは誰の？ — 私のです。',
     '<b>mía</b>：ser の後ろでは後置形を使う。maleta（女性単数）に一致して mía。'],
    ['Los libros no son [[míos|私の（後置形）]], son [[tuyos|君の（後置形）]].',
     'その本は私のではなく、君のだ。',
     '<b>míos / tuyos</b>：後置形は被所有物 libros（男性複数）に完全に一致する。'],
    ['Una amiga [[mía|私の（後置形）]] es profesora de inglés.',
     '私の友人の一人は英語の先生だ。',
     '<b>mía</b>：「un/una＋名詞＋後置形」で「私の〜のうちの一人」。amiga（女性単数）に一致。'],
    ['Las llaves son [[suyas|彼の（後置形）]].',
     'その鍵は彼のものだ。',
     '<b>suyas</b>：所有者（彼）ではなく、被所有物 llaves（女性複数）に一致させる。'],
    ['[[Hay|存在]] un banco cerca de la estación.',
     '駅の近くに銀行が1つある。',
     '<b>Hay</b>：不特定のもの（un banco）が「ある」ことを表すのは hay。'],
    ['[[Hay|存在（複数）]] muchos turistas en Kioto.',
     '京都には観光客がたくさんいる。',
     '<b>Hay</b>：hay は後ろの名詞が複数でも形が変わらない。×Han とはしない。'],
    ['En la clase [[hay|存在]] veinte estudiantes, pero la profesora no [[está|特定の人の所在]].',
     '教室には学生が20人いるが、先生はいない。',
     '<b>hay</b>：数を示して存在を述べる。<b>está</b>：特定の人（la profesora）の所在は estar。'],
    ['—¿[[Hay|存在を尋ねる]] una farmacia por aquí? —Sí, [[la|特定のもの]] farmacia [[está|所在]] en la esquina.',
     'この辺に薬局はありますか？ — はい、薬局は角にあります。',
     '<b>Hay</b>：あるかどうか分からない不特定の薬局 → hay＋不定冠詞。<b>la / está</b>：話題になった特定の薬局 → 定冠詞＋estar。'],
    ['No [[hay|存在の否定]] leche en la nevera.',
     '冷蔵庫に牛乳がない。',
     '<b>hay</b>：否定文でも hay の形は同じ。no は動詞の直前に置く。'],
    ['[[Tu|君の（前置形）]] libro [[está|所在]] en la mesa, pero el [[mío|私のもの]] no.',
     '君の本はテーブルの上にあるが、私のはない。',
     '<b>Tu</b>：名詞の前は前置形。<b>está</b>：特定の本の所在。<b>mío</b>：「el＋後置形」で「私のもの」を表す（el mío＝el libro mío）。'],
  ]},

  { num: '⑥', title: '文の構造・否定文・疑問詞', items: [
    ['¿[[De dónde|出身を尋ねる]] eres? — Soy de Perú.',
     'どこの出身？ — ペルー出身だよ。',
     '<b>De dónde</b>：出身は ser de なので、疑問詞にも de を付ける。'],
    ['¿[[Con quién|誰と]] vives? — Vivo con mi familia.',
     '誰と住んでいるの？ — 家族と住んでいるよ。',
     '<b>Con quién</b>：前置詞は疑問詞の前に置く（×¿Quién vives con?）。'],
    ['¿[[De quién|所有者を尋ねる]] es el coche rojo?',
     'その赤い車は誰のもの？',
     '<b>De quién</b>：所有は ser de＋人なので、「誰の」は de quién。'],
    ['¿[[Cuál|範囲の決まった答え]] es tu número de teléfono?',
     '君の電話番号は？',
     '<b>Cuál</b>：答えの範囲が決まっているもの（番号・住所・名前など）は cuál で尋ねる。qué は使わない。'],
    ['¿[[Cuántas|数を尋ねる]] personas hay en tu familia?',
     '君の家族は何人？',
     '<b>Cuántas</b>：cuánto は後ろの名詞に性数一致する。personas（女性複数）→ cuántas。'],
    ['¿[[Qué|疑問形容詞]] hora es? — [[Son|時刻（5時）]] las cinco.',
     '何時？ — 5時だよ。',
     '<b>Qué</b>：「何の・どの」＋名詞は qué。<b>Son</b>：las cinco（複数）なので son。'],
    ['¿[[Cuándo|時を尋ねる]] es tu cumpleaños?',
     '君の誕生日はいつ？',
     '<b>Cuándo</b>：「いつ」。イベント・日付は ser を使う。'],
    ['¿[[Cómo|人柄・性質を尋ねる]] es tu profesor? — Es alto y muy simpático.',
     '君の先生はどんな人？ — 背が高くて、とても感じがいいよ。',
     '<b>Cómo</b>：¿Cómo es…? は性質（どんな人・物か）、¿Cómo está…? は状態（調子はどうか）を尋ねる。'],
    ['¿[[A dónde|行き先を尋ねる]] vas? — Voy [[al|a ＋ el]] supermercado.',
     'どこへ行くの？ — スーパーへ行くよ。',
     '<b>A dónde</b>：行き先「どこへ」。<b>al</b>：a ＋ el supermercado の縮約。'],
    ['—¿Estás cansado? —No, [[no|否定]] estoy cansado.',
     '疲れてる？ — いや、疲れてないよ。',
     '<b>no</b>：最初の No は「いいえ」、2つ目の no は動詞の直前に置く否定語。答えでは No, no… と2回続くことがよくある。'],
    ['¿[[Quiénes|誰（複数）]] son los chicos de la foto?',
     '写真の男の子たちは誰？',
     '<b>Quiénes</b>：尋ねる相手が複数（son los chicos）なので quiénes。'],
    ['¿[[Por qué|理由を尋ねる]] estás triste? — [[Porque|理由を答える]] mi perro está enfermo.',
     'どうして悲しいの？ — 犬が病気だからだよ。',
     '<b>Por qué</b>：理由を問う疑問詞（2語・アクセント記号あり）。<b>Porque</b>：理由を答える接続詞（1語・アクセント記号なし）。'],
  ]},

  { num: '⑦', title: '総合（複数の文法の組み合わせ）', items: [
    ['[[La|定冠詞]] capital de Argentina [[es|補語]] Buenos Aires y [[está|所在]] en el este del país.',
     'アルゼンチンの首都はブエノスアイレスで、国の東部にある。',
     '<b>La</b>：capital は女性名詞。<b>es</b>：「首都＝ブエノスアイレス」は ser。<b>está</b>：所在は estar。'],
    ['En [[nuestra|私たちの]] universidad [[hay|存在]] [[muchos|数量]] estudiantes [[extranjeros|extranjero を一致させる]].',
     '私たちの大学には留学生がたくさんいる。',
     '<b>nuestra</b>：universidad（女性）に一致。<b>hay</b>：存在。<b>muchos / extranjeros</b>：estudiantes（男性複数）に一致。'],
    ['¿[[Dónde|場所]] [[están|所在・複数]] [[mis|私の（複数）]] llaves? — [[Están|所在]] [[sobre|〜の上に]] la mesa.',
     '私の鍵はどこ？ — テーブルの上にあるよ。',
     '<b>Dónde</b>：場所。<b>están</b>：特定の物（mis llaves：複数）の所在。<b>mis</b>：複数形。<b>sobre</b>：「〜の上に」。'],
    ['María [[es|国籍]] [[mexicana|mexicano の女性形]], pero ahora [[está|所在]] en Japón [[por|理由]] su trabajo.',
     'マリアはメキシコ人だが、今は仕事の都合で日本にいる。',
     '<b>es</b>：国籍は ser。<b>mexicana</b>：女性形。<b>está</b>：今いる場所。<b>por</b>：理由「〜のために・〜の都合で」。'],
    ['[[El|agua の冠詞]] agua [[del|de ＋ el]] mar [[está|状態]] muy fría hoy.',
     '今日は海の水がとても冷たい。',
     '<b>El</b>：agua は女性名詞だが単数では el。<b>del</b>：de ＋ el mar。<b>está</b>：「今日は冷たい」は一時的な状態。'],
    ['Mi abuelo es un [[gran|grande の短縮形]] hombre, pero hoy [[está|今日の状態]] muy [[cansado|cansado を一致させる]].',
     '私の祖父は偉大な人だが、今日はとても疲れている。',
     '<b>gran</b>：単数名詞の前で「偉大な」。<b>está</b>：一時的な状態。<b>cansado</b>：abuelo（男性単数）に一致。'],
    ['—¿[[Cómo|調子を尋ねる]] estás? —[[Estoy|estar・yo]] bien, pero [[mi|私の]] madre [[está|体調]] [[enferma|enfermo を一致させる]].',
     '元気？ — 私は元気だけど、母が病気なんだ。',
     '<b>Cómo</b>：調子を尋ねる。<b>Estoy / está</b>：体調は estar。<b>mi</b>：単数。<b>enferma</b>：madre（女性）に一致。'],
    ['Los estudiantes [[de|所属]] la clase [[son|性格]] [[simpáticos|simpático を一致させる]] y [[trabajadores|trabajador を一致させる]].',
     'そのクラスの学生たちは感じがよくて勤勉だ。',
     '<b>de</b>：所属「〜の」。<b>son</b>：性格は ser。<b>simpáticos / trabajadores</b>：男性複数に一致（trabajador ＋ es）。'],
    ['—¿[[De quién|所有者を尋ねる]] son las gafas? —Son [[mías|私の（後置形）]].',
     'その眼鏡は誰の？ — 私のです。',
     '<b>De quién</b>：所有者。<b>mías</b>：gafas（眼鏡）は常に女性複数形で使う名詞なので mías。'],
    ['[[Hay|存在]] un restaurante [[italiano|国籍形容詞]] muy [[bueno|名詞の後ろ]] [[en|場所]] la calle Mayor.',
     'マヨール通りにとてもおいしいイタリア料理店がある。',
     '<b>Hay</b>：不特定の店の存在。<b>italiano</b>：国籍形容詞は後置。<b>bueno</b>：名詞の<b>後ろ</b>なので短縮しない（buen は名詞の直前だけ）。<b>en</b>：場所。'],
  ]},
];

TANREN_SOURCE[3] = [
  { num: '①', title: '現在形の規則活用', items: [
    ['Mis padres [[trabajan|trabajar]] en un banco y yo [[estudio|estudiar]] en la universidad.',
     '私の両親は銀行で働いていて、私は大学で勉強している。',
     '<b>trabajan</b>：-ar 動詞の ellos 形は -an。<b>estudio</b>：yo 形は -o。'],
    ['¿Vosotros [[habláis|hablar]] inglés? — No, [[hablamos|hablar]] español y japonés.',
     '君たちは英語を話す？ — いや、スペイン語と日本語を話すよ。',
     '<b>habláis</b>：vosotros 形は -áis（アクセント記号が必要）。<b>hablamos</b>：nosotros 形は -amos。'],
    ['Los domingos mi familia no [[trabaja|trabajar]] y [[come|comer]] en casa de mis abuelos.',
     '毎週日曜日、私の家族は仕事をせず、祖父母の家で食事をする。',
     '<b>trabaja / come</b>：mi familia は1つの集団なので<b>3人称単数</b>。Los domingos は「毎週日曜日に」（習慣）。'],
    ['¿Qué [[bebes|beber]] tú? — Yo [[bebo|beber]] agua con gas.',
     '君は何を飲む？ — 私は炭酸水を飲むよ。',
     '<b>bebes / bebo</b>：-er 動詞の tú 形は -es、yo 形は -o。'],
    ['Ana [[escribe|escribir]] muchas cartas y [[recibe|recibir]] muchas respuestas.',
     'アナはたくさん手紙を書き、たくさん返事を受け取る。',
     '<b>escribe / recibe</b>：-ir 動詞の3人称単数は -e（-er 動詞と同じ）。'],
    ['Nosotros [[vivimos|vivir]] en Kioto y [[comemos|comer]] pescado a menudo.',
     '私たちは京都に住んでいて、よく魚を食べる。',
     '<b>vivimos</b>：-ir 動詞の nosotros 形は -imos。<b>comemos</b>：-er 動詞は -emos。ここが -er と -ir の違い。'],
    ['¿Dónde [[vivís|vivir]] vosotros? — [[Vivimos|vivir]] cerca de la estación.',
     '君たちはどこに住んでいるの？ — 駅の近くに住んでいるよ。',
     '<b>vivís</b>：-ir 動詞の vosotros 形は -ís（アクセント記号が必要）。-er 動詞なら -éis。'],
    ['Vosotros [[coméis|comer]] mucho pan.',
     '君たちはパンをたくさん食べる。',
     '<b>coméis</b>：-er 動詞の vosotros 形は -éis。-ir 動詞の -ís と区別する。'],
    ['Mañana mis amigos [[viajan|viajar]] a Perú.',
     '明日、私の友人たちはペルーへ旅立つ。',
     '<b>viajan</b>：現在形は「確実な近い未来」も表せる。Mañana があるので未来の予定だとわかる。'],
    ['El tren [[llega|llegar]] a las ocho y [[parte|partir]] a las ocho y diez.',
     'その電車は8時に着いて、8時10分に出発する。',
     '<b>llega</b>：-ar 動詞の3人称単数は -a。<b>parte</b>：-ir 動詞の3人称単数は -e。'],
    ['¿[[Aprendes|aprender]] español o portugués? — [[Aprendo|aprender]] español.',
     'スペイン語とポルトガル語、どっちを学んでいるの？ — スペイン語だよ。',
     '<b>Aprendes / Aprendo</b>：-er 動詞。tú → -es、yo → -o。主語は活用からわかるので省略できる。'],
    ['Mi hermano [[corre|correr]] en el parque todas las mañanas.',
     '私の兄（弟）は毎朝公園で走る。',
     '<b>corre</b>：-er 動詞の3人称単数は -e。todas las mañanas（毎朝）は習慣。'],
    ['En el mercado [[venden|vender]] fruta muy barata.',
     '市場ではとても安い果物を売っている。',
     '<b>venden</b>：主語を言わない3人称複数は「（一般の）人々が〜する」という意味になる。'],
    ['Los estudiantes [[abren|abrir]] los libros y [[leen|leer]] el texto.',
     '学生たちは本を開いて、文章を読む。',
     '<b>abren</b>：-ir 動詞の ellos 形は -en。<b>leen</b>：leer は現在形では規則的（leo, lees, lee…）。'],
    ['Tú [[comprendes|comprender]] bien, pero no [[hablas|hablar]] mucho.',
     '君はよく理解しているけれど、あまり話さない。',
     '<b>comprendes</b>：-er 動詞の tú 形は -es。<b>hablas</b>：-ar 動詞の tú 形は -as。'],
    ['Usted [[toma|tomar]] café con leche, ¿verdad?',
     'あなたはミルクコーヒーを飲みますよね？',
     '<b>toma</b>：usted は3人称単数扱いなので -a。tomar は「（飲み物を）飲む・（乗り物に）乗る・取る」。'],
    ['Ustedes [[suben|subir]] al tercer piso en ascensor.',
     'あなた方はエレベーターで3階へ上がる。',
     '<b>suben</b>：ustedes は3人称複数扱い。-ir 動詞なので -en。'],
    ['Yo [[preparo|preparar]] la cena y mi marido [[lava|lavar]] los platos.',
     '私が夕食を作り、夫が皿を洗う。',
     '<b>preparo</b>：yo 形は -o。<b>lava</b>：3人称単数は -a。'],
    ['¿A qué hora [[cenáis|cenar]] vosotros? — [[Cenamos|cenar]] a las nueve.',
     '君たちは何時に夕食をとるの？ — 9時に食べるよ。',
     '<b>cenáis</b>：vosotros 形 -áis（アクセント記号）。<b>Cenamos</b>：nosotros 形 -amos。'],
    ['Los estudiantes [[deben|deber]] llegar a las nueve.',
     '学生たちは9時に到着しなければならない。',
     '<b>deben</b>：deber＋不定詞で「〜しなければならない」。活用するのは deber だけで、llegar は不定詞のまま。'],
    ['Mi madre [[cocina|cocinar]] muy bien y todos [[comemos|comer]] mucho.',
     '母は料理がとても上手で、みんなたくさん食べる。',
     '<b>cocina</b>：3人称単数。<b>comemos</b>：「みんな（私たち）」なので nosotros 形。'],
    ['¿[[Escuchas|escuchar]] música cuando [[estudias|estudiar]]?',
     '君は勉強するとき音楽を聴く？',
     '<b>Escuchas / estudias</b>：どちらも -ar 動詞の tú 形（-as）。'],
    ['En México [[hablan|hablar]] español.',
     'メキシコではスペイン語を話す。',
     '<b>hablan</b>：一般的な事実を、主語なしの3人称複数で表す形。'],
    ['Yo [[desayuno|desayunar]] a las siete y [[llego|llegar]] a la oficina a las nueve.',
     '私は7時に朝食をとり、9時に会社に着く。',
     '<b>desayuno / llego</b>：どちらも -ar 動詞の yo 形（-o）。'],
    ['Carmen y yo [[compartimos|compartir]] un piso en Madrid.',
     'カルメンと私はマドリードでマンションをシェアしている。',
     '<b>compartimos</b>：Carmen y yo ＝ nosotros なので1人称複数。-ir 動詞は -imos。'],
  ]},

  { num: '②', title: '目的語と目的格代名詞', items: [
    ['Llamo [[a|特定の人が目的語]] mi madre todos los días.',
     '私は毎日母に電話する。',
     '<b>a</b>：直接目的語が特定の人（mi madre）のときは前置詞 a が必要。'],
    ['¿Compras el pan? — Sí, [[lo|el pan を]] compro.',
     'パンを買う？ — うん、それを買うよ。',
     '<b>lo</b>：el pan（男性単数）を受ける直接目的格代名詞。活用した動詞の直前に置く。'],
    ['¿Tomas la leche? — No, no [[la|la leche を]] tomo.',
     '牛乳を飲む？ — いや、それは飲まない。',
     '<b>la</b>：la leche（女性単数）を受ける。否定文では no → 代名詞 → 動詞 の順。'],
    ['¿Lees los periódicos? — Sí, [[los|los periódicos を]] leo.',
     '新聞を読む？ — うん、読むよ。',
     '<b>los</b>：los periódicos（男性複数）を受ける直接目的格代名詞。'],
    ['¿Escribes las cartas? — Sí, [[las|las cartas を]] escribo.',
     '手紙を書く？ — うん、それを書くよ。',
     '<b>las</b>：las cartas（女性複数）を受ける直接目的格代名詞。'],
    ['Mi profesor [[me|私に]] manda muchos correos.',
     '私の先生は私にたくさんメールを送ってくる。',
     '<b>me</b>：「私に」（間接目的格）。1・2人称は直接・間接で同じ形。'],
    ['¿[[Te|君に]] escribe María? — Sí, [[me|私に]] escribe todas las semanas.',
     'マリアは君に手紙を書いてくる？ — うん、毎週書いてくるよ。',
     '<b>Te / me</b>：間接目的格「君に」「私に」。質問の te は、答えでは me になる。'],
    ['[[Le|彼に（間接）]] regalo un libro a David.',
     '私はダビドに本をプレゼントする。',
     '<b>Le</b>：3人称の間接目的格は le。a David があっても le は省略しないのが普通。'],
    ['[[Les|彼らに（間接）]] preparo la cena a mis hijos.',
     '私は子どもたちに夕食を作る。',
     '<b>Les</b>：a mis hijos（複数）を受ける間接目的格は les。'],
    ['Le dejo las llaves. → [[Se|le の変化]] [[las|las llaves を]] dejo.',
     '彼（彼女）に鍵を置いていく。→ 彼（彼女）にそれを置いていく。',
     '<b>Se las</b>：間接 le と直接 las がどちらも3人称のとき、le は <b>se</b> に変わる。順番は間接 → 直接。'],
    ['¿Me prestas tu bicicleta? — Sí, [[te|君に]] [[la|自転車を]] presto.',
     '自転車を貸してくれる？ — うん、君に貸すよ。',
     '<b>te la</b>：間接（te）→ 直接（la＝bicicleta）の順。te は2人称なので se には変わらない。'],
    ['¿Le mandas el paquete a tu madre? — Sí, [[se|le の変化]] [[lo|el paquete を]] mando hoy.',
     'お母さんに小包を送るの？ — うん、今日送るよ。',
     '<b>se lo</b>：le ＋ lo → se lo。3人称どうしなので le が se になる。'],
    ['¿Nos vendes tu coche? — No, no [[os|君たちに]] [[lo|車を]] vendo.',
     '私たちに車を売ってくれる？ — いや、君たちには売らないよ。',
     '<b>os lo</b>：「私たちに」と聞かれたら「君たちに」の os で答える。間接 → 直接の順。'],
    ['Debo terminar el trabajo. → [[Lo|それを]] debo terminar. = Debo [[terminarlo|不定詞＋代名詞]].',
     '私はその仕事を終えなければならない。→ それを終えなければならない。',
     '<b>Lo / terminarlo</b>：不定詞があるときは、代名詞を活用した動詞の前に置いても、不定詞の後ろに1語で付けてもよい。'],
    ['Necesito comprar las entradas. → Necesito [[comprarlas|不定詞の後ろに付ける]].',
     '私はチケットを買う必要がある。→ それを買う必要がある。',
     '<b>comprarlas</b>：las entradas（女性複数）→ las を不定詞の後ろに付けて1語で書く。'],
    ['A [[ti|前置詞の後ろの「君」]] te invitan al concierto.',
     '（ほかでもない）君がコンサートに招待されている。',
     '<b>ti</b>：前置詞の後ろの「君」は ti（アクセント記号なし）。a ti は強調で、te は省略できない。'],
    ['Este regalo es para [[ti|前置詞の後ろの「君」]] y ese es para [[mí|前置詞の後ろの「私」]].',
     'このプレゼントは君への、それは私へのものだ。',
     '<b>ti / mí</b>：前置詞の後ろでは yo → mí（所有形容詞 mi と区別するためアクセント記号あり）、tú → ti。'],
    ['¿Estudias [[conmigo|con＋「私」]] esta tarde? — Sí, estudio [[contigo|con＋「君」]].',
     '今日の午後、私と一緒に勉強する？ — うん、君と一緒に勉強するよ。',
     '<b>conmigo / contigo</b>：con＋mí、con＋ti は特別な1語になる。'],
    ['Visito [[a|特定の人が目的語]] mis abuelos los domingos y [[les|彼らに]] llevo fruta.',
     '私は毎週日曜日に祖父母を訪ね、果物を持っていく。',
     '<b>a</b>：直接目的語が特定の人なので a が必要。<b>les</b>：「彼らに」（間接・複数）。'],
    ['Espero [[a|特定の人が目的語]] Carmen en la estación. [[La|彼女を]] espero desde las diez.',
     '私は駅でカルメンを待っている。10時から彼女を待っている。',
     '<b>a</b>：特定の人の前に a。<b>La</b>：Carmen（女性）を受ける直接目的格。代名詞には a を付けない。'],
    ['Llamo [[al|a＋el]] médico.',
     '私は医者を呼ぶ。',
     '<b>al</b>：特定の人（el médico）が直接目的語なので a が必要。a＋el → al。'],
    ['¿Escuchas a tus padres? — Sí, [[los|彼らを]] escucho.',
     '君は両親の言うことを聞く？ — うん、聞くよ。',
     '<b>los</b>：a tus padres（男性複数の人）を受ける直接目的格代名詞。'],
    ['¿Ayudas a tu madre? — Sí, [[la|彼女を]] ayudo en la cocina.',
     'お母さんを手伝う？ — うん、台所で手伝うよ。',
     '<b>la</b>：ayudar は「〜を手伝う」で直接目的語をとる。a tu madre（女性）→ la。'],
    ['Le pregunto la dirección al policía. → [[Se|le の変化]] [[la|la dirección を]] pregunto.',
     '警察官に住所を尋ねる。→ 彼にそれを尋ねる。',
     '<b>Se la</b>：le（警察官に）＋ la（住所を）→ se la。'],
    ['Juan y María [[nos|私たちを]] invitan a cenar.',
     'フアンとマリアは私たちを夕食に招待してくれる。',
     '<b>nos</b>：「私たちを」（直接目的格）。1人称複数は直接・間接とも nos。'],
  ]},

  { num: '③', title: 'gustar型動詞', items: [
    ['Me [[gustan|主語が複数]] las manzanas, pero no me [[gusta|主語が単数]] el plátano.',
     '私はリンゴが好きだが、バナナは好きではない。',
     '<b>gustan / gusta</b>：gustar は「好かれるもの」（主語）に合わせる。las manzanas は複数、el plátano は単数。'],
    ['A mi padre [[le|a mi padre を受ける]] [[gusta|主語は el vino]] mucho el vino.',
     '私の父はワインがとても好きだ。',
     '<b>le</b>：a mi padre があっても le は必要。<b>gusta</b>：el vino（単数）が主語。'],
    ['¿[[Te|君に]] gusta bailar? — Sí, me [[encanta|大好きだ]].',
     '君は踊るのが好き？ — うん、大好きだよ。',
     '<b>Te</b>：「君に」好かれる。<b>encanta</b>：encantar は gustar より強い「大好きだ」。不定詞（bailar）が主語なので単数。'],
    ['Nos [[gusta|主語は不定詞2つ]] cantar y bailar.',
     '私たちは歌ったり踊ったりするのが好きだ。',
     '<b>gusta</b>：不定詞が2つ以上並んでも<b>単数</b>扱い。gustan にはならない。'],
    ['A mis hijos no [[les|a mis hijos を受ける]] [[interesa|主語は la política]] la política.',
     '私の子どもたちは政治に興味がない。',
     '<b>les</b>：a mis hijos（複数）→ les。<b>interesa</b>：主語 la política（単数）に合わせる。人の数ではない。'],
    ['¿Os [[apetecen|主語が複数]] unas tapas?',
     '君たち、タパスを食べたい気分？',
     '<b>apetecen</b>：主語 unas tapas（複数）に合わせて -en。'],
    ['A [[mí|前置詞の後ろの「私」]] me gusta el té. ¿Y a [[ti|前置詞の後ろの「君」]]?',
     '私は紅茶が好き。君は？',
     '<b>mí / ti</b>：a の後ろでは mí（アクセント記号あり）と ti。'],
    ['—Me gusta el café. —A mí [[también|肯定に同意]].',
     'コーヒーが好きなんだ。 — 私も。',
     '<b>también</b>：肯定文に「私も」と同意するときは A mí también。'],
    ['—No me gusta el pescado. —A mí [[tampoco|否定に同意]].',
     '魚は好きじゃない。 — 私も好きじゃない。',
     '<b>tampoco</b>：否定文に「私も〜ない」と同意するときは A mí tampoco。también ではない。'],
    ['—No me gustan los gatos. —A mí [[sí|否定に反対]].',
     '猫は好きじゃない。 — 私は好きだよ。',
     '<b>sí</b>：否定文に対して「私は好き」と反対するときは A mí sí。'],
    ['—Me encanta la paella. —A mí [[no|肯定に反対]].',
     'パエリアが大好き。 — 私はそうでもない。',
     '<b>no</b>：肯定文に対して「私は違う」と反対するときは A mí no。'],
    ['¿Qué te [[parece|parecer]] esta ciudad? — Me [[parece|parecer]] muy bonita.',
     'この町をどう思う？ — とてもきれいだと思う。',
     '<b>parece</b>：parecer も gustar 型。主語 esta ciudad（単数）に合わせる。'],
    ['No me [[importa|importar]] el precio.',
     '私は値段は気にしない。',
     '<b>importa</b>：importar（〜にとって重要だ）も gustar 型。主語 el precio は単数。'],
    ['A Carmen le [[encantan|主語が複数]] los perros.',
     'カルメンは犬が大好きだ。',
     '<b>encantan</b>：主語 los perros（複数）に合わせる。'],
    ['Tú me [[gustas|主語は tú]] mucho, Ana.',
     'アナ、私は君のことがとても好きだ。',
     '<b>gustas</b>：好かれるのが「君（tú）」なので、gustar も tú の形 gustas になる。'],
    ['A nosotros [[nos|a nosotros を受ける]] interesan los idiomas.',
     '私たちは言語に興味がある。',
     '<b>nos</b>：a nosotros は強調。間接目的格 nos は必ず入れる。'],
    ['A ellas [[les|a ellas を受ける]] gusta leer novelas.',
     '彼女たちは小説を読むのが好きだ。',
     '<b>les</b>：a ellas（3人称複数）→ les。男女の区別はない。'],
    ['¿A usted [[le|usted を受ける]] apetece un café?',
     'コーヒーはいかがですか？',
     '<b>le</b>：usted は3人称扱いなので、間接目的格は le。'],
    ['A mí [[me|a mí とセットの代名詞]] gusta mucho la música cubana.',
     '私はキューバ音楽がとても好きだ。',
     '<b>me</b>：A mí gusta… ✗。a mí は強調なので、me は省略できない。'],
    ['A mis padres les [[gustan|主語が複数]] las películas españolas, pero a mí no [[me|私に]] [[gustan|主語が複数]].',
     '両親はスペイン映画が好きだが、私は好きではない。',
     '<b>gustan</b>：主語 las películas（複数）。<b>me</b>：a mí とセットで使う。'],
  ]},

  { num: '④', title: '指示詞', items: [
    ['[[Esta|近称・女性単数]] bolsa es mía y [[esa|中称・女性単数]] es tuya.',
     'このバッグは私ので、そっちのは君のだ。',
     '<b>Esta</b>：話し手の近くの bolsa（女性）。<b>esa</b>：聞き手の近くのもの。名詞を省略して代名詞として使っている。'],
    ['[[Estos|近称・男性複数]] zapatos son muy caros.',
     'この靴はとても高い。',
     '<b>Estos</b>：zapatos（男性複数）に一致する近称。'],
    ['¿Quién es [[aquella|遠称・女性単数]] chica?',
     'あの女の子は誰？',
     '<b>aquella</b>：話し手・聞き手のどちらからも遠い chica（女性単数）。'],
    ['¿Son tuyos [[esos|中称・男性複数]] libros?',
     '（君のそばにある）その本は君のもの？',
     '<b>esos</b>：聞き手の近くにある libros（男性複数）。'],
    ['[[Aquel|遠称・男性単数]] edificio es el hospital.',
     'あの建物は病院だ。',
     '<b>Aquel</b>：遠称の男性単数。語尾が -o ではないので注意（aquel / aquellos / aquella / aquellas）。'],
    ['¿Qué es [[eso|中称・中性]]? — Es un regalo para mi madre.',
     'それは何？ — 母へのプレゼントだよ。',
     '<b>eso</b>：何かわからない物を指すときは中性形。中性形は代名詞としてだけ使う。'],
    ['[[Esto|近称・中性]] es muy difícil para mí.',
     'これは私にはとても難しい。',
     '<b>Esto</b>：話し手の近くの事柄を漠然と指す中性形。'],
    ['Me gustan [[estas|近称・女性複数]] flores.',
     'この花（複数）が気に入った。',
     '<b>estas</b>：flores（女性複数）に一致。gustan も複数に合わせている。'],
    ['¿Cuál es tu paraguas? — Es [[aquel|遠称・男性単数]].',
     '君の傘はどれ？ — あれだよ。',
     '<b>aquel</b>：遠くにある paraguas（男性）を指す指示代名詞。'],
    ['[[Este|近称・男性単数]] año estudio francés.',
     '今年、私はフランス語を勉強している。',
     '<b>Este</b>：año（男性）。este año「今年」、esta semana「今週」のように時間にも使う。'],
    ['Ana, me gusta mucho [[ese|中称・男性単数]] vestido.',
     'アナ、そのドレスとても素敵だね。',
     '<b>ese</b>：相手（アナ）が着ている、つまり聞き手の近くにあるので中称。'],
    ['[[Aquellas|遠称・女性複数]] casas son muy antiguas.',
     'あの家々はとても古い。',
     '<b>Aquellas</b>：casas（女性複数）に一致する遠称。'],
    ['¿Qué es [[aquello|遠称・中性]]? — Es un templo.',
     'あれは何？ — お寺だよ。',
     '<b>aquello</b>：遠くにある、何かわからない物を指す中性形。'],
    ['[[Esta|近称・女性単数]] tarde estudiamos en la biblioteca.',
     '今日の午後、私たちは図書館で勉強する。',
     '<b>Esta</b>：tarde（女性）。esta tarde「今日の午後」。'],
    ['No compro [[esos|中称・男性複数]] tomates; compro [[estos|近称・男性複数]].',
     'そのトマトは買わないで、こっちのを買う。',
     '<b>esos / estos</b>：tomates（男性複数）。2つ目は名詞を省略した代名詞の用法。'],
  ]},

  { num: '⑤', title: '総合（複数の文法の組み合わせ）', items: [
    ['¿Compras [[estas|近称・女性複数]] naranjas? — Sí, [[las|naranjas を]] compro.',
     'このオレンジを買う？ — うん、買うよ。',
     '<b>estas</b>：naranjas（女性複数）に一致。<b>las</b>：同じく女性複数の直接目的格。'],
    ['A mi hermana le [[encantan|encantar]] estos chocolates y [[los|chocolates を]] [[come|comer]] todos los días.',
     '姉（妹）はこのチョコレートが大好きで、毎日食べている。',
     '<b>encantan</b>：主語 estos chocolates（複数）。<b>los</b>：chocolates を受ける。<b>come</b>：3人称単数。'],
    ['Mi madre [[me|私に]] [[prepara|preparar]] el desayuno todas las mañanas.',
     '母は毎朝私に朝食を作ってくれる。',
     '<b>me</b>：「私に」（間接）。<b>prepara</b>：mi madre なので3人称単数。'],
    ['¿[[Le|彼に]] escribes a Pedro? — Sí, [[le|彼に]] [[escribo|escribir]] un correo ahora.',
     'ペドロに手紙を書くの？ — うん、今メールを書くよ。',
     '<b>Le / le</b>：a Pedro を受ける間接目的格。<b>escribo</b>：yo 形。'],
    ['¿Quién [[vende|vender]] [[esas|中称・女性複数]] manzanas? — [[Las|manzanas を]] vende aquel señor.',
     'そのリンゴは誰が売っているの？ — あの男性が売っているよ。',
     '<b>vende</b>：quién は3人称単数扱い。<b>esas</b>：manzanas に一致。<b>Las</b>：manzanas を受ける直接目的格。'],
    ['—¿Te gusta el pescado? —Sí, me [[gusta|gustar]] y [[lo|el pescado を]] [[como|comer]] a menudo.',
     '魚は好き？ — うん、好きでよく食べるよ。',
     '<b>gusta</b>：el pescado（単数）。<b>lo</b>：el pescado を受ける。<b>como</b>：yo 形。'],
    ['¿Me [[prestas|prestar]] [[ese|中称・男性単数]] libro? — Sí, [[te|君に]] [[lo|本を]] presto.',
     'その本を貸してくれる？ — うん、貸すよ。',
     '<b>prestas</b>：tú 形。<b>ese</b>：相手の近くの本。<b>te lo</b>：間接 → 直接の順。'],
    ['A nosotros no [[nos|私たちに]] [[gusta|主語が単数]] [[esta|近称・女性単数]] música.',
     '私たちはこの音楽が好きではない。',
     '<b>nos</b>：a nosotros とセット。<b>gusta</b>：主語 esta música（単数）。<b>esta</b>：música（女性）。'],
    ['Mis amigos [[me|私を]] [[esperan|esperar]] en la estación.',
     '友人たちが駅で私を待っている。',
     '<b>me</b>：「私を」（直接）。<b>esperan</b>：mis amigos なので3人称複数。'],
    ['Este regalo es para [[ti|前置詞の後ろ]]. — ¡Gracias! [[Lo|regalo を]] [[abro|abrir]] ahora.',
     'このプレゼントは君にだよ。 — ありがとう！今開けるね。',
     '<b>ti</b>：前置詞 para の後ろ。<b>Lo</b>：el regalo を受ける。<b>abro</b>：abrir の yo 形。'],
    ['Los estudiantes [[deben|deber]] leer [[este|近称・男性単数]] libro y el profesor [[les|彼らに]] [[explica|explicar]] el contenido.',
     '学生たちはこの本を読まなければならず、先生が彼らに内容を説明する。',
     '<b>deben</b>：deber＋不定詞。<b>este</b>：libro（男性）。<b>les</b>：学生たちに（間接）。<b>explica</b>：3人称単数。'],
    ['¿Os [[interesa|主語が単数]] el arte? — Sí, [[nos|私たちに]] interesa mucho.',
     '君たちは芸術に興味がある？ — うん、とても興味があるよ。',
     '<b>interesa</b>：主語 el arte（単数）。<b>nos</b>：「君たちに」と聞かれたら「私たちに」の nos で答える。'],
    ['—¿Bebes vino? —No, no [[lo|vino を]] [[bebo|beber]]. —Yo [[tampoco|否定に同意]].',
     'ワインは飲む？ — いや、飲まない。 — 私も飲まない。',
     '<b>lo</b>：vino を受ける。<b>bebo</b>：yo 形。<b>tampoco</b>：否定に同意する「〜もまた…ない」。'],
    ['[[Aquella|遠称・女性単数]] señora [[vende|vender]] pan y siempre [[me|私に]] [[regala|regalar]] una galleta.',
     'あの女性はパンを売っていて、いつも私にクッキーをくれる。',
     '<b>Aquella</b>：señora（女性）。<b>vende / regala</b>：3人称単数。<b>me</b>：「私に」（間接）。'],
    ['¿Qué [[os|君たちに]] [[parece|parecer]] [[este|近称・男性単数]] restaurante? — Nos [[parece|parecer]] muy bueno.',
     'このレストランをどう思う？ — とてもいいと思う。',
     '<b>os</b>：「君たちに」。<b>parece</b>：主語 este restaurante（単数）。<b>este</b>：restaurante（男性）。'],
  ]},
];

TANREN_SOURCE[4] = [
  { num: '①', title: '直説法現在形不規則活用', items: [
    ['Yo [[quiero|querer]] un café, pero mi hermana [[prefiere|preferir]] un té.',
     '私はコーヒーが欲しいが、姉（妹）は紅茶のほうがいい。',
     '<b>quiero / prefiere</b>：どちらも e → ie 型。yo と3人称単数は語根が変化する。'],
    ['¿A qué hora [[empieza|empezar]] la clase? — [[Empieza|empezar]] a las nueve.',
     '授業は何時に始まる？ — 9時に始まるよ。',
     '<b>Empieza</b>：empezar は e → ie 型。主語 la clase は3人称単数。'],
    ['Nosotros no [[entendemos|entender]] la pregunta, pero ellos la [[entienden|entender]].',
     '私たちはその質問がわからないが、彼らはわかる。',
     '<b>entendemos</b>：nosotros 形は語根が変化しない（ブーツ型の外）。<b>entienden</b>：ellos 形は e → ie。'],
    ['¿[[Puedes|poder]] cerrar la ventana? — Sí, ahora la [[cierro|cerrar]].',
     '窓を閉めてくれる？ — うん、今閉めるよ。',
     '<b>Puedes</b>：poder は o → ue 型。<b>cierro</b>：cerrar は e → ie 型。'],
    ['Mis padres [[vuelven|volver]] a casa tarde y [[duermen|dormir]] poco.',
     '両親は遅く帰宅して、あまり眠らない。',
     '<b>vuelven / duermen</b>：どちらも o → ue 型。ellos 形は語根が変化する。'],
    ['¿Cuánto [[cuesta|costar]] este libro? — [[Cuesta|costar]] veinte euros.',
     'この本はいくら？ — 20ユーロだよ。',
     '<b>cuesta</b>：costar は o → ue 型。主語 este libro は3人称単数。'],
    ['No [[recuerdo|recordar]] su nombre. ¿Tú lo [[recuerdas|recordar]]?',
     '彼の名前を思い出せない。君は覚えてる？',
     '<b>recuerdo / recuerdas</b>：recordar は o → ue 型。yo・tú 形で語根が変化する。'],
    ['En el restaurante siempre [[pido|pedir]] paella y mi novio [[pide|pedir]] pescado.',
     'レストランで私はいつもパエリアを頼み、彼氏は魚を頼む。',
     '<b>pido / pide</b>：pedir は e → i 型（-ir 動詞だけにある型）。'],
    ['Los estudiantes [[repiten|repetir]] las palabras del profesor.',
     '学生たちは先生の言葉を繰り返す。',
     '<b>repiten</b>：repetir は e → i 型。語根の2つ目の e が i に変わる（repetir → repiten）。'],
    ['Nosotros [[jugamos|jugar]] al tenis y los niños [[juegan|jugar]] al fútbol.',
     '私たちはテニスをして、子どもたちはサッカーをする。',
     '<b>jugamos</b>：nosotros 形は変化しない。<b>juegan</b>：jugar だけの u → ue 型。「〜をする」は jugar a＋競技（a＋el → al）。'],
    ['Yo no [[conozco|conocer]] Madrid, pero [[sé|saber]] que es una ciudad muy bonita.',
     '私はマドリードに行ったことはないが、とてもきれいな町だということは知っている。',
     '<b>conozco</b>：-zco 型。経験として「知っている」。<b>sé</b>：saber の yo 形。情報として「知っている」。'],
    ['[[Conduzco|conducir]] al trabajo todos los días.',
     '私は毎日車で仕事に行く。',
     '<b>Conduzco</b>：母音＋cir で終わる動詞は yo 形が -zco になる。'],
    ['¿Qué [[haces|hacer]] los fines de semana? — [[Hago|hacer]] deporte.',
     '週末は何をしている？ — スポーツをしているよ。',
     '<b>haces</b>：tú 形は規則どおり。<b>Hago</b>：yo 形だけ -go になる。'],
    ['[[Salgo|salir]] de casa a las ocho y [[pongo|poner]] la radio en el coche.',
     '私は8時に家を出て、車でラジオをつける。',
     '<b>Salgo / pongo</b>：どちらも yo 形だけが -go になる純粋 -go 型。'],
    ['¿[[Tienes|tener]] hermanos? — Sí, [[tengo|tener]] dos hermanas.',
     '兄弟はいる？ — うん、姉妹が2人いるよ。',
     '<b>Tienes</b>：tú 形は e → ie。<b>tengo</b>：yo 形は -go 型で、語根母音は変化しない。'],
    ['Yo [[vengo|venir]] a la universidad en tren, pero Ana [[viene|venir]] en bicicleta.',
     '私は電車で大学に来るが、アナは自転車で来る。',
     '<b>vengo</b>：yo 形は -go 型。<b>viene</b>：3人称単数は e → ie。tener と同じパターン。'],
    ['Siempre [[digo|decir]] la verdad, pero tú [[dices|decir]] mentiras.',
     '私はいつも本当のことを言うが、君は嘘を言う。',
     '<b>digo</b>：decir は yo 形でも e → i が起こる（tener・venir との違い）。<b>dices</b>：e → i。'],
    ['¿Me [[oyes|oír]]? — Sí, te [[oigo|oír]] bien.',
     '私の声、聞こえる？ — うん、よく聞こえるよ。',
     '<b>oyes</b>：oír は tú・él・ellos 形で y が入る。<b>oigo</b>：yo 形は -igo。'],
    ['Yo [[traigo|traer]] el vino y vosotros [[traéis|traer]] el pan.',
     '私がワインを持ってくるから、君たちはパンを持ってきて。',
     '<b>traigo</b>：traer は yo 形が -igo。<b>traéis</b>：vosotros 形は規則どおり。'],
    ['¿A dónde [[vas|ir]]? — [[Voy|ir]] a la biblioteca.',
     'どこに行くの？ — 図書館に行くよ。',
     '<b>vas / Voy</b>：ir は完全な不規則動詞（voy, vas, va, vamos, vais, van）。'],
    ['Yo te [[doy|dar]] mi número y tú me [[das|dar]] el tuyo.',
     '私は君に自分の番号を教えるから、君は私に君のを教えて。',
     '<b>doy</b>：dar の yo 形は -oy（soy, voy, estoy と同じ）。<b>das</b>：tú 形は規則的。'],
    ['Desde aquí [[veo|ver]] el mar.',
     'ここから海が見える。',
     '<b>veo</b>：ver の yo 形は veo（×vo）。ほかは ves, ve, vemos, veis, ven。'],
    ['Yo no [[quepo|caber]] en este coche.',
     '私はこの車には乗れない（入らない）。',
     '<b>quepo</b>：caber の yo 形は quepo という特殊な形。'],
    ['Los niños [[construyen|construir]] un castillo de arena.',
     '子どもたちは砂の城を作っている。',
     '<b>construyen</b>：-uir 動詞は nosotros・vosotros 以外で y が入る。'],
    ['El ladrón [[huye|huir]] de la policía.',
     '泥棒は警察から逃げる。',
     '<b>huye</b>：huir も -uir 動詞なので、3人称単数で y が入る。'],
    ['¿[[Piensas|pensar]] ir a la fiesta? — No, [[prefiero|preferir]] estudiar en casa.',
     'パーティーに行くつもり？ — いや、家で勉強するほうがいい。',
     '<b>Piensas</b>：pensar＋不定詞で「〜するつもりだ」。e → ie 型。<b>prefiero</b>：e → ie 型。'],
    ['Mi hijo [[mide|medir]] un metro y medio.',
     '私の息子は身長1メートル50センチだ。',
     '<b>mide</b>：medir は e → i 型。「身長が〜ある」は medir で表す。'],
    ['Esta película no [[vale|valer]] la pena.',
     'この映画は見る価値がない。',
     '<b>vale</b>：valer は yo 形だけが -go（valgo）。3人称単数は規則どおり。valer la pena「〜する価値がある」。'],
    ['[[Tengo que|tener que＋不定詞]] estudiar esta noche.',
     '私は今夜勉強しなければならない。',
     '<b>Tengo que</b>：tener que＋不定詞で「（特定の人が）〜しなければならない」。'],
    ['Mañana [[vamos a|ir a＋不定詞]] visitar a mis abuelos.',
     '明日、私たちは祖父母を訪ねるつもりだ。',
     '<b>vamos a</b>：ir a＋不定詞で「〜するつもりだ・〜するだろう」（近い未来）。'],
  ]},

  { num: '②', title: '関係詞', items: [
    ['Tengo un amigo [[que|関係代名詞]] habla cinco idiomas.',
     '私には5か国語を話す友人がいる。',
     '<b>que</b>：先行詞 un amigo が関係節の主語。人にも物にも使える。'],
    ['El libro [[que|関係代名詞]] leo ahora es muy interesante.',
     '私が今読んでいる本はとても面白い。',
     '<b>que</b>：先行詞 el libro が関係節の直接目的語（leo el libro）。'],
    ['La ciudad [[donde|場所の関係副詞]] vive mi abuela es muy pequeña.',
     '祖母が住んでいる町はとても小さい。',
     '<b>donde</b>：場所を表す名詞が先行詞のとき「〜する所」。'],
    ['No entiendo [[lo que|先行詞のない「こと」]] dice el profesor.',
     '先生の言っていることがわからない。',
     '<b>lo que</b>：「〜すること・もの」。抽象的な内容を指すので中性の lo。'],
    ['[[Lo que|「〜すること」]] quiero es dormir.',
     '私がしたいのは眠ることだ。',
     '<b>Lo que</b>：先行詞のない独立用法。「私が欲しい（したい）こと」。'],
    ['Esa es la casa [[en la que|vivir en ＋ la casa]] vivo.',
     'それが私の住んでいる家だ。',
     '<b>en la que</b>：vivir en la casa なので前置詞 en が必要。casa（女性単数）に合わせて la que。'],
    ['El chico [[con el que|salir con ＋ el chico]] sale mi hermana es mexicano.',
     '姉（妹）が付き合っている男の子はメキシコ人だ。',
     '<b>con el que</b>：salir con 〜「〜と付き合う」。chico（男性単数）なので el que。'],
    ['Tengo dos hijos, [[a los que|enseñar a ＋ 人]] enseño español todas las noches.',
     '私には2人の子どもがいて、毎晩彼らにスペイン語を教えている。',
     '<b>a los que</b>：「彼らに」教えるので前置詞 a。hijos（男性複数）なので los que。'],
    ['Los estudiantes [[que|限定用法]] estudian mucho aprueban el examen.',
     'よく勉強する学生は試験に合格する。',
     '<b>que</b>：カンマなしの限定用法。「学生のうち、よく勉強する学生」と範囲を絞る。'],
    ['Mi hermano, [[que|説明用法]] vive en Chile, viene a Japón en agosto.',
     '私の兄は、チリに住んでいるのだが、8月に日本に来る。',
     '<b>que</b>：カンマで区切る説明用法。先行詞について情報を付け足す。'],
    ['[[La que|先行詞なし・女性単数]] canta es mi hermana.',
     '歌っているのは私の姉（妹）だ。',
     '<b>La que</b>：先行詞なしで「〜する人」。女性1人を指すので la que。'],
    ['[[Los que|先行詞なし・男性複数]] quieren ir a la excursión tienen que venir a las ocho.',
     '遠足に行きたい人は8時に来なければならない。',
     '<b>Los que</b>：「〜する人たち」。男女混合・不特定の複数は los que。'],
    ['Este no es el tren [[que|関係代名詞]] tomo todos los días.',
     'これは私が毎日乗る電車ではない。',
     '<b>que</b>：tomo el tren の el tren が先行詞（直接目的語）。前置詞は不要。'],
    ['La razón [[por la que|por ＋ la razón]] estudio español es mi novia.',
     '私がスペイン語を勉強する理由は彼女だ。',
     '<b>por la que</b>：理由の por が必要。razón（女性単数）なので la que。'],
    ['El bolígrafo [[con el que|escribir con ＋ 道具]] escribo es de mi padre.',
     '私が書くのに使っているボールペンは父のものだ。',
     '<b>con el que</b>：「〜で書く」の con。bolígrafo（男性単数）なので el que。'],
    ['Este es el restaurante [[donde|場所の関係副詞]] comemos los domingos.',
     'ここが私たちが毎週日曜日に食事をするレストランだ。',
     '<b>donde</b>：場所が先行詞。en el que と言い換えることもできる。'],
    ['No sé [[lo que|先行詞のない「もの」]] quieres.',
     '君が何を欲しいのかわからない。',
     '<b>lo que</b>：「君が欲しいもの」。saber の目的語になっている。'],
    ['Las chicas [[a las que|invitar a ＋ 人]] invito a la fiesta son mis compañeras.',
     '私がパーティーに招待する女の子たちは同級生だ。',
     '<b>a las que</b>：人が直接目的語なので a が必要。chicas（女性複数）なので las que。'],
    ['Aquí es [[donde|独立用法・場所]] trabaja mi padre.',
     'ここが父の働いている所だ。',
     '<b>donde</b>：先行詞なしで「〜する所」を表す独立用法。'],
    ['Los libros [[de los que|hablar de ＋ 物]] hablamos son muy caros.',
     '私たちが話している本はとても高い。',
     '<b>de los que</b>：hablar de 〜「〜について話す」。libros（男性複数）なので los que。'],
  ]},

  { num: '③', title: '比較表現', items: [
    ['Mi hermana es [[más|優等比較]] [[alta|alto を一致させる]] [[que|比較の対象]] yo.',
     '姉（妹）は私より背が高い。',
     '<b>más … que</b>：優等比較。<b>alta</b>：形容詞は主語 mi hermana（女性）に一致させる。'],
    ['Esta corbata es [[menos|劣等比較]] bonita [[que|比較の対象]] esa.',
     'このネクタイはそれほどかっこよくない。',
     '<b>menos … que</b>：劣等比較「〜ほど…ではない」。'],
    ['Mi casa es [[tan|同等比較]] grande [[como|同等比較の対応語]] la tuya.',
     '私の家は君の家と同じくらい大きい。',
     '<b>tan … como</b>：同等比較。que ではなく como を使う。'],
    ['Juan corre [[más|優等比較]] [[rápido|副詞]] que sus hermanas.',
     'フアンは姉妹たちより速く走る。',
     '<b>rápido</b>：ここでは動詞 corre を修飾する副詞なので、性数変化しない（×rápidas）。'],
    ['Este restaurante es [[mejor|bueno の比較級]] que aquel.',
     'このレストランはあのレストランよりいい。',
     '<b>mejor</b>：bueno の比較級は más bueno ではなく mejor。'],
    ['Mi español es [[peor|malo の比較級]] que el tuyo.',
     '私のスペイン語は君のより下手だ。',
     '<b>peor</b>：malo の比較級は peor。<b>el tuyo</b>＝tu español。'],
    ['Mi abuela es [[mayor|年齢の比較]] que mi abuelo.',
     '祖母は祖父より年上だ。',
     '<b>mayor</b>：年齢の「より上」は mayor。más grande は物理的な大きさ。'],
    ['Mis primos son [[menores|年齢の比較・複数]] que yo.',
     'いとこたちは私より年下だ。',
     '<b>menores</b>：menor の複数形。主語 mis primos に数を一致させる。'],
    ['Tokio es [[más grande|物理的な大きさ]] que Osaka.',
     '東京は大阪より大きい。',
     '<b>más grande</b>：物理的な大きさの比較は más grande（mayor は年齢・抽象的な大小）。'],
    ['Tengo [[tantos|mucho の同等比較]] libros [[como|同等比較の対応語]] tú.',
     '私は君と同じくらいたくさんの本を持っている。',
     '<b>tantos</b>：tan＋mucho → tanto。libros（男性複数）に一致して tantos。'],
    ['No tengo [[tanta|mucho の同等比較]] paciencia como mi madre.',
     '私は母ほど忍耐強くない。',
     '<b>tanta</b>：paciencia（女性単数）に一致する。'],
    ['Ella estudia [[tanto|副詞の同等比較]] como su hermano.',
     '彼女は兄（弟）と同じくらい勉強する。',
     '<b>tanto</b>：動詞を修飾する副詞なので性数変化しない。'],
    ['Nuestro jefe lee [[más de|数量の前]] cinco periódicos al día.',
     '私たちの上司は毎日5紙以上の新聞を読む。',
     '<b>más de</b>：数量の前では que ではなく de を使う。'],
    ['Este problema es [[más|優等比較]] difícil [[de lo que|lo que の前]] piensas.',
     'この問題は君が思っているより難しい。',
     '<b>de lo que</b>：比較の相手が節（lo que piensas）のときは que ではなく de。'],
    ['Trabajas [[más de|lo＋形容詞の前]] lo necesario.',
     '君は必要以上に働いている。',
     '<b>más de</b>：lo＋形容詞（lo necesario）の前でも de を使う。'],
    ['Emilio es [[el más alto|最上級]] de su familia.',
     'エミリオは家族の中で一番背が高い。',
     '<b>el más alto</b>：最上級は「定冠詞＋más＋形容詞＋de＋範囲」。'],
    ['Estas manzanas son [[las más caras|最上級・女性複数]] del mercado.',
     'このリンゴは市場で一番高い。',
     '<b>las más caras</b>：manzanas（女性複数）に定冠詞も形容詞も一致させる。範囲は de＋el → del。'],
    ['Es el [[mejor|bueno の最上級]] restaurante de la ciudad.',
     'そこは町で一番いいレストランだ。',
     '<b>mejor</b>：el mejor＋名詞で「一番いい〜」。mejor は名詞の前に置ける。'],
    ['Es la persona [[más feliz|最上級]] del mundo.',
     '彼（彼女）は世界で一番幸せな人だ。',
     '<b>más feliz</b>：la persona の後ろに más＋形容詞。「世界で」は del mundo。'],
    ['Carmen es [[la que|副詞の最上級]] corre más rápido de la clase.',
     'カルメンはクラスで一番速く走る人だ。',
     '<b>la que</b>：副詞の最上級は「定冠詞＋que＋動詞＋más＋副詞」の形で表す。'],
    ['Quiero estar aquí un minuto [[más|「あと〜」]].',
     'あと1分ここにいたい。',
     '<b>más</b>：名詞の後ろに置くと「さらに・あと〜」の意味になる。'],
    ['Estos zapatos son [[menos|劣等比較]] caros que esos, pero son [[peores|malo の比較級・複数]].',
     'この靴はそれより安いが、質が悪い。',
     '<b>menos</b>：劣等比較。<b>peores</b>：peor の複数形。主語 zapatos に数を一致させる。'],
    ['Mi coche es más viejo que [[el tuyo|君のもの]].',
     '私の車は君のより古い。',
     '<b>el tuyo</b>：「定冠詞＋所有形容詞後置形」で「君のもの」。coche（男性単数）に一致。'],
    ['Pablo tiene [[menos|劣等比較]] años [[que|比較の対象]] su novia.',
     'パブロは彼女より年下だ。',
     '<b>menos … que</b>：名詞（años）の前に menos を置いて「〜より少ない」。'],
    ['[[Lo mejor|最もよいこと]] de este viaje es la comida.',
     'この旅行で一番いいのは食べ物だ。',
     '<b>Lo mejor</b>：中性の lo＋mejor で「最もよいこと」。'],
  ]},

  { num: '④', title: '無主語文', items: [
    ['¿Qué tiempo [[hace|天候]] hoy? — [[Hace|天候]] mucho calor.',
     '今日はどんな天気？ — とても暑いよ。',
     '<b>hace</b>：天候は hacer の3人称単数で表す。主語はない。'],
    ['En invierno [[hace|天候]] frío y [[nieva|nevar]] mucho en Hokkaido.',
     '冬、北海道は寒くて雪がたくさん降る。',
     '<b>hace</b>：hace frío。<b>nieva</b>：nevar（e → ie）の3人称単数。'],
    ['En junio [[llueve|llover]] mucho en Japón.',
     '日本では6月にたくさん雨が降る。',
     '<b>llueve</b>：llover（o → ue）の3人称単数。'],
    ['Hoy [[hace|天候]] [[buen|bueno の短縮形]] tiempo.',
     '今日は天気がいい。',
     '<b>hace</b>：天候。<b>buen</b>：男性単数名詞 tiempo の前なので bueno → buen。'],
    ['¿Qué hora es? — [[Es|1時台]] la una y cuarto.',
     '何時？ — 1時15分だよ。',
     '<b>Es</b>：1時台は la una（単数）なので es。cuarto は「15分（4分の1）」。'],
    ['[[Son|2時以降]] las siete [[menos|〜分前]] cuarto.',
     '6時45分だ。',
     '<b>Son … menos</b>：「7時15分前」＝6時45分。30分を過ぎたら次の時刻から menos で引く。'],
    ['[[Son|2時以降]] las cinco y [[media|30分]].',
     '5時半だ。',
     '<b>Son</b>：複数。<b>media</b>：30分（2分の1）。'],
    ['La clase empieza [[a|〜時に]] las diez [[en punto|ちょうど]].',
     '授業は10時ちょうどに始まる。',
     '<b>a</b>：「〜時に」は a las 〜。<b>en punto</b>：「ちょうど」。'],
    ['Es la una de la [[madrugada|深夜]].',
     '夜中の1時だ。',
     '<b>madrugada</b>：深夜0時過ぎから夜明けまで。de la mañana（午前）より前の時間帯。'],
    ['[[Hay que|一般論の義務]] estudiar mucho para aprobar.',
     '合格するにはたくさん勉強しなければならない。',
     '<b>Hay que</b>：主語のない一般論「（人は）〜しなければならない」。'],
    ['Para viajar al extranjero [[hay que|一般論の義務]] tener pasaporte.',
     '外国を旅行するにはパスポートが必要だ。',
     '<b>hay que</b>：一般的なルール。特定の人の義務なら tener que。'],
    ['Hoy [[está|状態]] nublado.',
     '今日は曇っている。',
     '<b>está</b>：「曇っている」は estar＋nublado（主語なし）。'],
    ['Ya [[es|季節]] primavera.',
     'もう春だ。',
     '<b>es</b>：季節・時期は ser の3人称単数で表す。'],
    ['Me [[basta|bastar]] con un vaso de agua.',
     '私は水1杯で十分だ。',
     '<b>basta</b>：bastar con 〜「〜で十分だ」。3人称単数で使う。'],
    ['¿A qué hora [[termina|terminar]] la película? — Termina [[a las|〜時に]] once menos cuarto de la noche.',
     '映画は何時に終わる？ — 夜10時45分に終わるよ。',
     '<b>termina</b>：主語 la película。<b>a las</b>：「〜時に」。once menos cuarto＝10時45分。'],
  ]},

  { num: '⑤', title: '総合（複数の文法の組み合わせ）', items: [
    ['El hotel [[donde|場所の関係副詞]] [[dormimos|dormir]] esta noche es [[más|優等比較]] caro que el otro.',
     '今夜私たちが泊まるホテルは、もう一方より高い。',
     '<b>donde</b>：場所。<b>dormimos</b>：nosotros 形は語根が変化しない。<b>más</b>：優等比較。'],
    ['[[Hace|天候]] tanto frío que no [[puedo|poder]] salir.',
     'とても寒くて外に出られない。',
     '<b>Hace</b>：天候。tanto＋名詞＋que で「とても〜なので…」。<b>puedo</b>：o → ue。'],
    ['Mi hermano [[mayor|年上の]] [[tiene|tener]] un coche [[que|関係代名詞]] [[cuesta|costar]] mucho dinero.',
     '兄はとても高い車を持っている。',
     '<b>mayor</b>：mi hermano mayor「兄」。<b>tiene</b>：e → ie。<b>que</b>：先行詞 un coche。<b>cuesta</b>：o → ue。'],
    ['[[Lo que|「〜すること」]] más me gusta de Madrid es la comida.',
     'マドリードで私が一番好きなのは食べ物だ。',
     '<b>Lo que</b>：「私が一番好きなこと」。más を入れると最上級の意味になる。'],
    ['—¿[[Sabes|saber]] a qué hora sale el tren? —Sí, [[sale|salir]] [[a|時刻]] las seis y media.',
     '電車が何時に出るか知ってる？ — うん、6時半に出るよ。',
     '<b>Sabes</b>：情報を知っているので saber。<b>sale</b>：3人称単数は規則どおり。<b>a</b>：「〜時に」。'],
    ['Este es el [[mejor|最上級]] libro [[que|関係代名詞]] [[conozco|conocer]].',
     'これは私が知っている中で一番いい本だ。',
     '<b>mejor</b>：el mejor＋名詞。<b>que</b>：関係代名詞。<b>conozco</b>：-zco 型。'],
    ['Cuando [[llueve|llover]], mis hijos [[juegan|jugar]] en casa.',
     '雨が降ると、子どもたちは家で遊ぶ。',
     '<b>llueve</b>：o → ue。<b>juegan</b>：u → ue（jugar だけ）。'],
    ['La chica [[con la que|con＋女性単数]] [[vengo|venir]] a clase es [[menor|年下]] que yo.',
     '私が一緒に授業に来る女の子は、私より年下だ。',
     '<b>con la que</b>：venir con 〜。<b>vengo</b>：-go 型。<b>menor</b>：年齢の比較。'],
    ['[[Tengo que|個人の義務]] ir al médico, pero [[hay que|一般論の義務]] pedir cita antes.',
     '私は医者に行かなければならないが、事前に予約を取る必要がある。',
     '<b>Tengo que</b>：私の個人的な義務。<b>hay que</b>：一般的なルール。'],
    ['¿[[Conoces|conocer]] a la profesora [[que|関係代名詞]] [[viene|venir]] de México? Es [[la más|最上級]] simpática de la escuela.',
     'メキシコから来る先生を知ってる？ 学校で一番感じのいい人だよ。',
     '<b>Conoces</b>：人を知っているので conocer（a が必要）。<b>que</b>：関係代名詞。<b>viene</b>：e → ie。<b>la más</b>：最上級。'],
  ]},
];

TANREN_SOURCE[5] = [
  { num: '①', title: '不定詞', items: [
    ['[[Fumar|名詞として使う]] es malo para la salud.',
     'たばこを吸うことは健康に悪い。',
     '<b>Fumar</b>：不定詞はそのまま「〜すること」という名詞として主語になれる。'],
    ['Siempre me lavo las manos antes de [[comer|前置詞の後ろ]].',
     '私はいつも食べる前に手を洗う。',
     '<b>comer</b>：前置詞（antes de）の後ろの動詞は不定詞にする。'],
    ['Ana sale de casa sin [[desayunar|sin＋動詞]].',
     'アナは朝食をとらずに家を出る。',
     '<b>desayunar</b>：sin＋不定詞で「〜せずに」。'],
    ['No sé [[qué|何を]] [[regalarle|regalar＋「彼女に」]] a mi madre.',
     '母に何をプレゼントすればいいかわからない。',
     '<b>qué</b>：疑問詞＋不定詞で「何を〜すべきか」。<b>regalarle</b>：代名詞 le を不定詞の後ろに付けて1語に。'],
    ['No sabemos [[cómo|どうやって]] llegar a la estación.',
     '私たちは駅への行き方がわからない。',
     '<b>cómo</b>：cómo＋不定詞で「どうやって〜すればいいか」。'],
    ['No sé [[dónde|どこに]] aparcar el coche.',
     'どこに車を停めればいいかわからない。',
     '<b>dónde</b>：dónde＋不定詞で「どこで〜すべきか」。'],
    ['Oigo [[cantar|知覚動詞の後ろ]] a los pájaros cada mañana.',
     '毎朝、鳥たちが歌うのが聞こえる。',
     '<b>cantar</b>：oír・ver＋不定詞で「〜が…するのが聞こえる・見える」。'],
    ['Veo a mis hijos [[jugar|知覚動詞の後ろ]] en el jardín.',
     '子どもたちが庭で遊ぶのが見える。',
     '<b>jugar</b>：知覚動詞＋人＋不定詞。不定詞は動作全体（一回の出来事）を表す。'],
    ['Mi jefe siempre me [[hace|強制的に〜させる]] trabajar los sábados.',
     '上司はいつも私に土曜日に働かせる。',
     '<b>hace</b>：hacer＋不定詞で「（強制的に）〜させる」。'],
    ['Mis padres no me [[dejan|〜させておく・許す]] ver la tele después de las diez.',
     '両親は10時以降、私にテレビを見させてくれない。',
     '<b>dejan</b>：dejar＋不定詞で「〜させておく・〜するのを許す」（放任使役）。'],
    ['El profesor nos [[hace|強制的に〜させる]] [[repetir|動詞の原形]] las frases.',
     '先生は私たちに文を繰り返させる。',
     '<b>hace</b>：強制使役。<b>repetir</b>：hacer の後ろは不定詞のまま（×repetimos）。'],
    ['Me gusta [[escuchar|gustar の主語]] música antes de [[dormir|前置詞の後ろ]].',
     '私は寝る前に音楽を聴くのが好きだ。',
     '<b>escuchar</b>：不定詞が gustar の主語になる。<b>dormir</b>：前置詞の後ろは不定詞。'],
  ]},

  { num: '②', title: '現在分詞（形と用法・不規則形）', items: [
    ['¿Qué estás [[haciendo|hacer]]? — Estoy [[estudiando|estudiar]] para el examen.',
     '何してるの？ — 試験の勉強をしているところだよ。',
     '<b>haciendo</b>：-er 動詞は -iendo。<b>estudiando</b>：-ar 動詞は -ando。estar＋現在分詞で進行形。'],
    ['Los niños están [[jugando|jugar]] en el parque.',
     '子どもたちは公園で遊んでいる。',
     '<b>jugando</b>：現在分詞は語根母音変化しない（×juegando）。'],
    ['Mi madre cocina [[escuchando|escuchar]] la radio.',
     '母はラジオを聴きながら料理をする。',
     '<b>escuchando</b>：現在分詞で「〜しながら」（同時の動作）。'],
    ['Los estudiantes están [[leyendo|leer]] en la biblioteca.',
     '学生たちは図書館で読書をしている。',
     '<b>leyendo</b>：語根が母音で終わる動詞は -iendo ではなく -yendo。'],
    ['El bebé está [[durmiendo|dormir]].',
     '赤ちゃんは眠っている。',
     '<b>durmiendo</b>：dormir は現在分詞で o → u になる。'],
    ['¿Qué me estás [[diciendo|decir]]?',
     '私に何を言っているの？',
     '<b>diciendo</b>：decir は現在分詞で e → i になる。'],
    ['El camarero está [[sirviendo|servir]] la comida.',
     'ウェイターが料理を出しているところだ。',
     '<b>sirviendo</b>：現在形で e → i 型の -ir 動詞は、現在分詞でも e → i。'],
    ['Estamos [[oyendo|oír]] música.',
     '私たちは音楽を聴いている。',
     '<b>oyendo</b>：oír は -yendo 型。'],
    ['Los obreros están [[construyendo|construir]] un puente.',
     '作業員たちが橋を建設している。',
     '<b>construyendo</b>：-uir 動詞は -yendo 型。'],
    ['Mis amigos están [[viniendo|venir]] a mi casa.',
     '友人たちが私の家に向かっている。',
     '<b>viniendo</b>：venir は現在分詞で e → i になる（現在形の e → ie とは違う）。'],
    ['Aprendemos mucho [[viajando|viajar]] por el mundo.',
     '私たちは世界を旅することで多くを学ぶ。',
     '<b>viajando</b>：現在分詞で「〜することで」（手段）。'],
    ['¿[[Sigues|seguir]] [[trabajando|trabajar]] en el mismo banco?',
     'まだ同じ銀行で働いているの？',
     '<b>Sigues</b>：seguir（e → i）の tú 形。<b>trabajando</b>：seguir＋現在分詞で「〜し続ける」。'],
    ['[[Llevamos|llevar]] dos años [[estudiando|estudiar]] español.',
     '私たちはスペイン語を勉強して2年になる。',
     '<b>Llevamos … estudiando</b>：llevar＋期間＋現在分詞で「〜し続けて（期間）になる」。'],
    ['El precio de la gasolina [[va|ir]] [[subiendo|subir]] poco a poco.',
     'ガソリンの値段が少しずつ上がっていく。',
     '<b>va subiendo</b>：ir＋現在分詞で「だんだん〜していく」。'],
    ['Lo estoy leyendo. = Estoy [[leyéndolo|代名詞を後ろに付ける]].',
     '私はそれを読んでいるところだ。',
     '<b>leyéndolo</b>：代名詞を現在分詞の後ろに付けると、強勢の位置を保つためアクセント記号が必要。'],
    ['Te estoy escribiendo un correo. = Estoy [[escribiéndote|代名詞を後ろに付ける]] un correo.',
     '君にメールを書いているところだよ。',
     '<b>escribiéndote</b>：te を後ろに付けて1語に。アクセント記号を忘れない。'],
    ['Cada tarde veo a mi vecino [[paseando|pasear]] con su perro.',
     '毎日午後、隣人が犬と散歩しているのを見かける。',
     '<b>paseando</b>：知覚動詞＋現在分詞は「〜しているところ」（進行中の動作）を強調する。'],
    ['[[Estudiando|estudiar]] mucho, vas a aprobar.',
     'たくさん勉強すれば、合格するだろう。',
     '<b>Estudiando</b>：現在分詞で「〜すれば」（条件）を表す。'],
    ['Mis padres siguen [[viviendo|vivir]] en el pueblo.',
     '両親は今も村に住み続けている。',
     '<b>viviendo</b>：seguir＋現在分詞。-ir 動詞は -iendo。'],
    ['Está [[cayendo|caer]] mucha nieve.',
     '雪がたくさん降っている。',
     '<b>cayendo</b>：caer は語根が母音で終わるので -yendo。'],
  ]},

  { num: '③', title: '過去分詞（形と用法）', items: [
    ['La puerta está [[abierta|abrir]].',
     'ドアが開いている。',
     '<b>abierta</b>：abrir の過去分詞は不規則形 abierto。puerta（女性）に一致させる。'],
    ['Las ventanas están [[rotas|romper]].',
     '窓が割れている。',
     '<b>rotas</b>：romper → roto（不規則）。ventanas（女性複数）に一致。'],
    ['Este libro está [[escrito|escribir]] en español.',
     'この本はスペイン語で書かれている。',
     '<b>escrito</b>：escribir → escrito（不規則）。'],
    ['La cena ya está [[hecha|hacer]].',
     '夕食はもうできている。',
     '<b>hecha</b>：hacer → hecho（-cho 型）。cena（女性）に一致。'],
    ['Las hojas [[caídas|caer]] cubren el suelo.',
     '落ち葉が地面を覆っている。',
     '<b>caídas</b>：語根が a・e・o で終わる -er/-ir 動詞は -ído とアクセント記号が付く。'],
    ['Esta es una novela muy [[leída|leer]] en España.',
     'これはスペインでよく読まれている小説だ。',
     '<b>leída</b>：leer → leído（アクセント記号必要）。novela（女性）に一致。'],
    ['La paella es un plato muy [[conocido|conocer]] en todo el mundo.',
     'パエリアは世界中でよく知られた料理だ。',
     '<b>conocido</b>：規則形（-er → -ido）。plato（男性）に一致。'],
    ['El museo es [[visitado|visitar]] por muchos turistas.',
     'その美術館は多くの観光客に訪れられている。',
     '<b>visitado</b>：ser＋過去分詞＋por＋行為者で受身「〜される」。'],
    ['Estas obras son [[admiradas|admirar]] por todo el mundo.',
     'これらの作品は世界中の人々に称賛されている。',
     '<b>admiradas</b>：受身の過去分詞は主語 obras（女性複数）に性数一致する。'],
    ['Las tiendas están [[cerradas|cerrar]] los domingos.',
     '日曜日は店が閉まっている。',
     '<b>cerradas</b>：estar＋過去分詞は「〜された状態にある」（結果の状態）。'],
    ['Llegamos muy [[cansados|cansar]] a casa.',
     '私たちはとても疲れて家に着く。',
     '<b>cansados</b>：主語（nosotros）を説明する主格補語。主語に性数一致させる。'],
    ['Te veo muy [[preocupada|preocupar]], Ana.',
     'アナ、とても心配そうだね。',
     '<b>preocupada</b>：ver＋目的語＋過去分詞で「〜が…の状態に見える」。Ana（女性）に一致。'],
    ['El problema está [[resuelto|resolver]].',
     'その問題は解決している。',
     '<b>resuelto</b>：resolver → resuelto（不規則）。'],
    ['La mesa está [[puesta|poner]].',
     '食卓の準備ができている。',
     '<b>puesta</b>：poner → puesto（不規則）。mesa に一致。poner la mesa「食卓を整える」。'],
    ['Me gustan mucho los huevos [[fritos|freír]].',
     '私は目玉焼き（揚げ焼きの卵）が大好きだ。',
     '<b>fritos</b>：freír → frito（不規則）。huevos（男性複数）に一致。'],
    ['El pez está [[muerto|morir]].',
     'その魚は死んでいる。',
     '<b>muerto</b>：morir → muerto（不規則）。'],
    ['La carta está [[impresa|imprimir]].',
     'その手紙は印刷されている。',
     '<b>impresa</b>：imprimir → impreso（-so 型）。carta（女性）に一致。'],
    ['La casa está [[cubierta|cubrir]] de nieve.',
     '家は雪に覆われている。',
     '<b>cubierta</b>：cubrir → cubierto（不規則）。casa に一致。'],
  ]},

  { num: '④', title: '現在完了', items: [
    ['¿Ya [[has leído|leer（tú）]] esta novela? — No, todavía no la [[he leído|leer（yo）]].',
     'もうこの小説読んだ？ — いや、まだ読んでいないよ。',
     '<b>has leído / he leído</b>：haber の現在形＋過去分詞。完了用法「もう〜した」。'],
    ['¿Ya [[habéis hecho|hacer（vosotros）]] la tarea?',
     '君たちはもう宿題をした？',
     '<b>habéis hecho</b>：vosotros → habéis。hacer の過去分詞は hecho。'],
    ['Nosotros nunca [[hemos estado|estar（nosotros）]] en México.',
     '私たちは一度もメキシコに行ったことがない。',
     '<b>hemos estado</b>：経験用法。「〜に行ったことがある」は estar の現在完了で表せる。'],
    ['¿[[Has visto|ver（tú）]] alguna vez un tiburón?',
     '今までにサメを見たことある？',
     '<b>Has visto</b>：alguna vez（今までに）は経験用法のサイン。ver → visto。'],
    ['Hoy [[he comido|comer（yo）]] con mis compañeros.',
     '今日は同僚と昼食をとった。',
     '<b>he comido</b>：hoy など現在を含む時の表現には、スペインでは現在完了を使う。'],
    ['Este año mis padres [[han viajado|viajar（ellos）]] a Europa dos veces.',
     '今年、両親はヨーロッパに2回旅行した。',
     '<b>han viajado</b>：este año（今年）なので現在完了。'],
    ['¿Quién [[ha abierto|abrir]] la ventana?',
     '誰が窓を開けたの？',
     '<b>ha abierto</b>：quién は3人称単数扱い。abrir → abierto。'],
    ['Los niños [[han roto|romper]] el jarrón.',
     '子どもたちが花瓶を割ってしまった。',
     '<b>han roto</b>：romper → roto。完了用法「〜してしまった」。'],
    ['Mi hermana [[ha escrito|escribir]] una novela.',
     '姉（妹）は小説を書き上げた。',
     '<b>ha escrito</b>：escribir → escrito。'],
    ['¿Qué te [[han dicho|decir（ellos）]]?',
     '彼らは君に何て言ったの？',
     '<b>han dicho</b>：decir → dicho。'],
    ['Todavía no [[hemos resuelto|resolver]] el problema.',
     '私たちはまだその問題を解決していない。',
     '<b>hemos resuelto</b>：todavía no＋現在完了で「まだ〜していない」。'],
    ['María [[ha vuelto|volver]] de Perú esta semana.',
     'マリアは今週ペルーから戻ってきた。',
     '<b>ha vuelto</b>：volver → vuelto。esta semana なので現在完了。'],
    ['Mis amigas [[han llegado|llegar]] tarde.',
     '友人たち（女性）は遅れて着いた。',
     '<b>han llegado</b>：完了時制の過去分詞は主語の性数に関係なく常に -o（×llegadas）。'],
    ['¿[[Habéis puesto|poner（vosotros）]] la mesa?',
     '君たち、食卓の準備はした？',
     '<b>Habéis puesto</b>：poner → puesto。'],
    ['[[Ha habido|hay の現在完了]] un accidente en la calle.',
     '通りで事故があった。',
     '<b>Ha habido</b>：hay（haber の無人称形）の現在完了。常に3人称単数。'],
    ['Hasta ahora siempre [[he vivido|vivir（yo）]] en esta ciudad.',
     '今までずっとこの町に住んできた。',
     '<b>he vivido</b>：継続用法「今までずっと〜してきた」。'],
    ['¿Ya [[te has levantado|levantarse（tú）]]?',
     'もう起きた？',
     '<b>te has levantado</b>：再帰代名詞は haber の前に置く。'],
    ['Este mes [[ha llovido|llover]] mucho.',
     '今月はたくさん雨が降った。',
     '<b>ha llovido</b>：天候の動詞も3人称単数の現在完了にできる。'],
  ]},

  { num: '⑤', title: '再帰動詞', items: [
    ['¿Cómo [[te llamas|llamarse（tú）]]? — [[Me llamo|llamarse（yo）]] Kenta.',
     '名前は何？ — ケンタだよ。',
     '<b>te llamas / Me llamo</b>：llamarse「〜という名前だ」（自分自身を〜と呼ぶ）。'],
    ['Yo [[me levanto|levantarse]] a las seis y [[me acuesto|acostarse]] a las once.',
     '私は6時に起きて11時に寝る。',
     '<b>me levanto</b>：起床する。<b>me acuesto</b>：acostarse は o → ue 型。'],
    ['Los domingos [[me despierto|despertarse]] tarde.',
     '日曜日はいつも遅く目が覚める。',
     '<b>me despierto</b>：despertarse は e → ie 型。'],
    ['¿[[Te lavas|lavarse（tú）]] las manos antes de comer?',
     '食べる前に手を洗う？',
     '<b>Te lavas</b>：間接再帰用法。「自分の手を」なので、所有形容詞ではなく定冠詞（las manos）を使う。'],
    ['Hace frío. ¿Por qué no [[te pones|ponerse（tú）]] el abrigo?',
     '寒いよ。コートを着たら？',
     '<b>te pones</b>：ponerse＋衣服で「〜を身につける」。poner の tú 形は pones。'],
    ['En Japón, la gente [[se quita|quitarse]] los zapatos en casa.',
     '日本では、人々は家で靴を脱ぐ。',
     '<b>se quita</b>：la gente は形は単数なので3人称単数。quitarse「（身につけた物を）脱ぐ」。'],
    ['Mi madre [[se pone|ponerse＋形容詞]] nerviosa antes de los exámenes.',
     '母は試験の前になると緊張する。',
     '<b>se pone</b>：ponerse＋形容詞で「〜の状態になる」。'],
    ['Tengo que [[acostarme|acostarse（yo）]] temprano esta noche.',
     '今夜は早く寝なければならない。',
     '<b>acostarme</b>：不定詞で使うときは -se を主語（yo）に合わせて -me にする。'],
    ['Vamos a [[levantarnos|levantarse（nosotros）]] a las cinco mañana.',
     '明日、私たちは5時に起きるつもりだ。',
     '<b>levantarnos</b>：ir a＋不定詞。主語 nosotros に合わせて -nos。'],
    ['Los novios [[se abrazan|abrazarse]] en la estación.',
     '恋人たちは駅で抱き合う。',
     '<b>se abrazan</b>：相互再帰用法「互いに〜し合う」。主語は複数。'],
    ['Mis abuelos [[se quieren|quererse]] mucho.',
     '祖父母はとても愛し合っている。',
     '<b>se quieren</b>：相互再帰用法。querer は e → ie 型。'],
    ['—¿Ya [[os vais|irse（vosotros）]]? —Sí, [[nos vamos|irse（nosotros）]] ya.',
     'もう帰っちゃうの？ — うん、もう行くよ。',
     '<b>os vais / nos vamos</b>：irse「（その場から）立ち去る」。ir の活用に再帰代名詞を付ける。'],
    ['Mi hermano [[se come|comerse]] toda la pizza.',
     '兄（弟）はピザを全部平らげてしまう。',
     '<b>se come</b>：強意用法。comerse「すっかり食べてしまう」。'],
    ['[[Me muero|morirse]] de sed.',
     'のどが渇いて死にそうだ。',
     '<b>Me muero</b>：morirse de 〜「〜で死にそうだ」（誇張）。o → ue 型。'],
    ['Jesús siempre [[se queja|quejarse]] de su trabajo.',
     'ヘススはいつも仕事の文句を言っている。',
     '<b>se queja</b>：quejarse de 〜は再帰の形でしか使わない動詞。'],
    ['Nadie [[se atreve|atreverse]] a hablar con el jefe.',
     '誰も上司と話す勇気がない。',
     '<b>se atreve</b>：atreverse a＋不定詞「あえて〜する」。nadie は3人称単数扱い。'],
    ['[[Se me ocurre|ocurrirse（私に）]] una buena idea.',
     'いい考えが浮かんだ。',
     '<b>Se me ocurre</b>：ocurrirse は「（考えが）人に浮かぶ」。考え（una idea）が主語で、人は間接目的格（me）。'],
    ['En Brasil [[se habla|受身の se（単数）]] portugués.',
     'ブラジルではポルトガル語が話されている。',
     '<b>se habla</b>：受身再帰用法。主語 portugués（単数）に合わせる。'],
    ['En esta tienda [[se venden|受身の se（複数）]] libros usados.',
     'この店では古本が売られている。',
     '<b>se venden</b>：主語 libros（複数）なので動詞も複数。'],
    ['¿Cómo [[se dice|不定主語の se]] "gracias" en japonés?',
     '「gracias」は日本語で何と言いますか？',
     '<b>se dice</b>：不定主語用法「（人は）〜と言う」。常に3人称単数。'],
    ['¿Cuánto tiempo [[se tarda|不定主語の se]] de Tokio a Osaka en tren?',
     '東京から大阪まで電車でどのくらいかかりますか？',
     '<b>se tarda</b>：tardar「時間がかかる」の不定主語用法。'],
    ['En este pueblo [[se vive|不定主語の se]] muy bien.',
     'この村はとても暮らしやすい。',
     '<b>se vive</b>：不定主語用法。主語がないので常に単数。'],
  ]},

  { num: '⑥', title: '総合（複数の文法の組み合わせ）', items: [
    ['Mi hermana [[se ha puesto|ponerse（現在完了）]] enferma por trabajar demasiado.',
     '姉（妹）は働きすぎて病気になってしまった。',
     '<b>se ha puesto</b>：再帰代名詞＋haber＋過去分詞。poner → puesto。enferma は主語に一致。'],
    ['¿[[Has visto|ver（現在完了）]] a Juan? — Sí, está [[durmiendo|dormir]] en su habitación.',
     'フアンを見かけた？ — うん、自分の部屋で寝ているよ。',
     '<b>Has visto</b>：ver → visto。<b>durmiendo</b>：o → u の不規則現在分詞。'],
    ['Esta mañana [[me he levantado|levantarse（現在完了）]] muy [[cansado|cansar]].',
     '今朝、私はとても疲れて起きた。',
     '<b>me he levantado</b>：esta mañana なので現在完了。<b>cansado</b>：主語（男性）に一致する主格補語。'],
    ['No sé qué [[decirte|decir＋te]]. [[Estoy|状態]] muy [[sorprendido|sorprender]].',
     '君に何と言えばいいかわからない。とても驚いている。',
     '<b>decirte</b>：疑問詞＋不定詞＋代名詞。<b>Estoy sorprendido</b>：estar＋過去分詞で状態。'],
    ['Los niños están [[jugando|jugar]] y la cena todavía no está [[hecha|hacer]].',
     '子どもたちは遊んでいて、夕食はまだできていない。',
     '<b>jugando</b>：進行形。<b>hecha</b>：estar＋過去分詞。cena（女性）に一致。'],
    ['[[Se han vendido|受身の se＋現在完了]] todas las entradas.',
     'チケットはすべて売り切れた。',
     '<b>Se han vendido</b>：受身再帰を現在完了にした形。主語 las entradas（複数）なので han。'],
    ['Mi padre me [[hace|使役]] lavar el coche y después [[me ducho|ducharse]].',
     '父は私に車を洗わせ、そのあと私はシャワーを浴びる。',
     '<b>hace</b>：hacer＋不定詞で強制使役。<b>me ducho</b>：ducharse「シャワーを浴びる」。'],
    ['¿Qué [[habéis dicho|decir（vosotros）]]? No os [[he oído|oír（yo）]].',
     '君たち、何て言ったの？ 聞こえなかった。',
     '<b>habéis dicho</b>：decir → dicho。<b>he oído</b>：oír → oído（アクセント記号必要）。'],
    ['[[Llevo|llevar]] una hora [[esperándote|esperar＋te]].',
     '私は君を1時間待っている。',
     '<b>Llevo … esperándote</b>：llevar＋期間＋現在分詞。te を付けたのでアクセント記号が必要。'],
    ['¿Por qué no [[te pones|ponerse]] el abrigo? Estás [[temblando|temblar]] de frío.',
     'コートを着たら？ 寒さで震えているよ。',
     '<b>te pones</b>：ponerse＋衣服。<b>temblando</b>：estar＋現在分詞。現在分詞は語根母音変化しない（×tiemblando）。'],
  ]},
];

TANREN_SOURCE[6] = [
  { num: '①', title: '点過去形・規則活用', items: [
    ['Ayer yo [[trabajé|trabajar]] hasta las ocho.',
     '昨日、私は8時まで働いた。',
     '<b>trabajé</b>：-ar 動詞の yo 形は -é（アクセント記号あり）。'],
    ['¿[[Hablaste|hablar（tú）]] con el profesor? — Sí, [[hablé|hablar（yo）]] con él ayer.',
     '先生と話した？ — うん、昨日話したよ。',
     '<b>Hablaste</b>：tú 形は -aste（アクセント記号なし）。<b>hablé</b>：yo 形は -é。'],
    ['Mi hermana [[compró|comprar]] un coche el mes pasado.',
     '姉（妹）は先月車を買った。',
     '<b>compró</b>：-ar 動詞の3人称単数は -ó。記号がないと compro（現在・yo）と区別できない。'],
    ['Anoche nosotros [[cenamos|cenar]] en un restaurante italiano.',
     '昨夜、私たちはイタリア料理店で夕食をとった。',
     '<b>cenamos</b>：-ar 動詞の nosotros 形は現在形と同じ形。anoche で過去だとわかる。'],
    ['Mis padres [[viajaron|viajar]] a Perú en 2019.',
     '両親は2019年にペルーへ旅行した。',
     '<b>viajaron</b>：-ar 動詞の3人称複数は -aron。'],
    ['¿Vosotros [[estudiasteis|estudiar（vosotros）]] para el examen?',
     '君たちは試験のために勉強した？',
     '<b>estudiasteis</b>：vosotros 形は -asteis（アクセント記号なし）。'],
    ['Yo [[comí|comer（yo）]] paella y mi novio [[bebió|beber]] vino.',
     '私はパエリアを食べ、彼氏はワインを飲んだ。',
     '<b>comí</b>：-er/-ir 動詞の yo 形は -í。<b>bebió</b>：3人称単数は -ió。'],
    ['¿Dónde [[viviste|vivir（tú）]] el año pasado?',
     '去年はどこに住んでいたの？',
     '<b>viviste</b>：-er/-ir 動詞の tú 形は -iste。'],
    ['Ellos [[vendieron|vender]] su casa en 2020.',
     '彼らは2020年に家を売った。',
     '<b>vendieron</b>：-er/-ir 動詞の3人称複数は -ieron。'],
    ['Ayer [[recibí|recibir（yo）]] una carta de mi abuela.',
     '昨日、祖母から手紙を受け取った。',
     '<b>recibí</b>：-ir 動詞の yo 形 -í。'],
    ['La semana pasada [[escribimos|escribir]] un informe.',
     '先週、私たちは報告書を書いた。',
     '<b>escribimos</b>：-ir 動詞の nosotros 形は現在形と同じ。la semana pasada（先週）で過去。'],
    ['¿[[Abrió|abrir]] usted la ventana?',
     'あなたが窓を開けたのですか？',
     '<b>Abrió</b>：usted は3人称単数扱い。-ir 動詞なので -ió。'],
    ['Mi hijo [[nació|nacer]] el 3 de mayo.',
     '私の息子は5月3日に生まれた。',
     '<b>nació</b>：nacer は点過去では規則どおり。'],
    ['El partido [[empezó|empezar]] a las ocho.',
     '試合は8時に始まった。',
     '<b>empezó</b>：点過去では語根母音は変化しない（×empiezó）。3人称単数は -ó。'],
    ['¿A qué hora [[volvisteis|volver（vosotros）]] anoche?',
     '君たちは昨夜何時に帰ってきたの？',
     '<b>volvisteis</b>：volver は点過去では規則どおり（-er 動詞なので語根変化しない）。'],
    ['Los estudiantes [[aprendieron|aprender]] mucho en el curso.',
     '学生たちは講座でたくさん学んだ。',
     '<b>aprendieron</b>：-er 動詞の3人称複数 -ieron。'],
    ['Me [[gustó|gustar]] mucho la película.',
     'その映画はとても気に入った。',
     '<b>gustó</b>：主語 la película（単数）に合わせて3人称単数。'],
    ['Me [[encantaron|encantar]] los tacos.',
     'タコスがすごくおいしかった。',
     '<b>encantaron</b>：主語 los tacos（複数）に合わせて3人称複数。'],
    ['Al llegar a casa, [[cené|cenar（yo）]] y me [[acosté|acostarse（yo）]].',
     '家に着くと、夕食をとって寝た。',
     '<b>cené / acosté</b>：-ar 動詞の yo 形 -é。al＋不定詞で「〜したとき」。'],
    ['Mis amigos me [[invitaron|invitar]] a cenar.',
     '友人たちが私を夕食に誘ってくれた。',
     '<b>invitaron</b>：-ar 動詞の3人称複数 -aron。'],
  ]},

  { num: '②', title: '不規則①　語根母音変化動詞', items: [
    ['Ella [[durmió|dormir]] ocho horas anoche.',
     '彼女は昨夜8時間眠った。',
     '<b>durmió</b>：-ir の語根母音変化動詞は、3人称で o → u。'],
    ['Mis hijos [[pidieron|pedir]] helado de postre.',
     '子どもたちはデザートにアイスクリームを頼んだ。',
     '<b>pidieron</b>：3人称複数で e → i。'],
    ['Yo [[pedí|pedir（yo）]] un café y mi amiga [[pidió|pedir（3人称）]] un té.',
     '私はコーヒーを、友人は紅茶を頼んだ。',
     '<b>pedí</b>：yo 形は変化しない。<b>pidió</b>：3人称単数だけ e → i。'],
    ['Nosotros [[dormimos|dormir（nosotros）]] en un hotel y ellos [[durmieron|dormir（ellos）]] en casa de un amigo.',
     '私たちはホテルに泊まり、彼らは友人の家に泊まった。',
     '<b>dormimos</b>：nosotros 形は変化しない。<b>durmieron</b>：3人称複数は o → u。'],
    ['¿Qué [[sintió|sentir]] usted al oír la noticia?',
     'その知らせを聞いたとき、あなたはどう感じましたか？',
     '<b>sintió</b>：usted は3人称扱いなので e → i。'],
    ['Mi abuelo [[murió|morir]] en 2015.',
     '祖父は2015年に亡くなった。',
     '<b>murió</b>：morir も3人称で o → u。'],
    ['El camarero nos [[sirvió|servir]] la comida.',
     'ウェイターが私たちに料理を出してくれた。',
     '<b>sirvió</b>：servir は3人称で e → i。'],
    ['Los niños [[siguieron|seguir]] al profesor.',
     '子どもたちは先生のあとについて行った。',
     '<b>siguieron</b>：seguir は3人称で e → i。'],
    ['Ana se [[vistió|vestirse]] rápidamente.',
     'アナは急いで服を着た。',
     '<b>vistió</b>：vestir(se) は3人称で e → i。'],
    ['El profesor [[repitió|repetir]] la pregunta dos veces.',
     '先生は質問を2回繰り返した。',
     '<b>repitió</b>：repetir の2つ目の e が i に変わる。'],
    ['¿Qué carrera [[eligió|elegir]] tu hermano?',
     '君のお兄さん（弟さん）はどの学部を選んだの？',
     '<b>eligió</b>：elegir は3人称で e → i。'],
    ['Ella [[sonrió|sonreír]] al verme.',
     '彼女は私を見て微笑んだ。',
     '<b>sonrió</b>：sonreír は3人称で ri- になる。son-rió と2音節なのでアクセント記号が付く。'],
    ['Todos [[se rieron|reírse（ellos）]] del chiste.',
     'みんなその冗談に笑った。',
     '<b>se rieron</b>：reír の3人称複数は rieron。reírse de 〜「〜を笑う」。'],
    ['¿Tú te [[reíste|reírse（tú）]] también?',
     '君も笑った？',
     '<b>reíste</b>：reír の tú 形。二重母音にならないよう í にアクセント記号が必要。'],
    ['Mis padres [[prefirieron|preferir]] quedarse en casa.',
     '両親は家にいるほうを選んだ。',
     '<b>prefirieron</b>：preferir（現在 e → ie 型）は点過去の3人称で e → i。'],
    ['El niño le [[mintió|mentir]] a su madre.',
     'その子は母親に嘘をついた。',
     '<b>mintió</b>：mentir は3人称で e → i。'],
    ['Nosotros no [[sentimos|sentir（nosotros）]] nada.',
     '私たちは何も感じなかった。',
     '<b>sentimos</b>：nosotros 形は変化しない。現在形と同じ形。'],
    ['¿Cuántas horas [[dormiste|dormir（tú）]] anoche? — [[Dormí|dormir（yo）]] solo cinco horas.',
     '昨夜は何時間寝た？ — 5時間しか寝てないよ。',
     '<b>dormiste / Dormí</b>：1・2人称は語根が変化しない。'],
  ]},

  { num: '③', title: '不規則②　3人称のみ語尾が変化する動詞', items: [
    ['Ella [[leyó|leer]] el libro en un día.',
     '彼女はその本を1日で読んだ。',
     '<b>leyó</b>：語根が母音で終わるので -ió → -yó。'],
    ['Los niños [[leyeron|leer]] muchos cuentos.',
     '子どもたちはたくさんの物語を読んだ。',
     '<b>leyeron</b>：3人称複数は -ieron → -yeron。'],
    ['¿[[Leíste|leer（tú）]] el periódico? — Sí, lo [[leí|leer（yo）]] ayer.',
     '新聞読んだ？ — うん、昨日読んだよ。',
     '<b>Leíste</b>：二重母音を防ぐため í にアクセント記号。<b>leí</b>：yo 形。'],
    ['Nadie [[creyó|creer]] su historia.',
     '誰も彼の話を信じなかった。',
     '<b>creyó</b>：creer も3人称で -yó。nadie は3人称単数扱い。'],
    ['Nosotros no [[creímos|creer（nosotros）]] lo que dijo.',
     '私たちは彼の言ったことを信じなかった。',
     '<b>creímos</b>：nosotros 形は y にならないが、í にアクセント記号が必要。'],
    ['El vaso se [[cayó|caerse]] al suelo.',
     'コップが床に落ちた。',
     '<b>cayó</b>：caer は3人称で -yó。'],
    ['Me [[caí|caerse（yo）]] en la calle.',
     '私は道で転んだ。',
     '<b>caí</b>：yo 形は y にならない。'],
    ['¿[[Oíste|oír（tú）]] ese ruido?',
     'あの音、聞こえた？',
     '<b>Oíste</b>：oír の tú 形。アクセント記号が必要。'],
    ['Los vecinos [[oyeron|oír]] gritos.',
     '近所の人たちが叫び声を聞いた。',
     '<b>oyeron</b>：oír の3人称複数は -yeron。'],
    ['El ladrón [[huyó|huir]] por la ventana.',
     '泥棒は窓から逃げた。',
     '<b>huyó</b>：-uir 動詞も3人称で -yó。'],
    ['Los romanos [[construyeron|construir]] este puente.',
     'ローマ人がこの橋を建設した。',
     '<b>construyeron</b>：-uir 動詞の3人称複数は -yeron。'],
    ['El hotel [[incluyó|incluir]] el desayuno en el precio.',
     'ホテルは料金に朝食を含めた。',
     '<b>incluyó</b>：-uir 動詞の3人称単数。'],
    ['Yo [[construí|construir（yo）]] esta casa con mis manos.',
     '私はこの家を自分の手で建てた。',
     '<b>construí</b>：yo 形は y にならない。-uir 動詞でアクセント記号が付くのは yo 形だけ。'],
    ['Vosotros [[leísteis|leer（vosotros）]] la novela entera.',
     '君たちは小説を最後まで読んだ。',
     '<b>leísteis</b>：語根が開母音で終わる動詞は vosotros 形にもアクセント記号。'],
    ['Las hojas [[cayeron|caer]] de los árboles.',
     '木から葉が落ちた。',
     '<b>cayeron</b>：caer の3人称複数。'],
  ]},

  { num: '④', title: '不規則③　強変化動詞', items: [
    ['Yo [[estuve|estar（yo）]] en Madrid el verano pasado.',
     '私は去年の夏マドリードにいた。',
     '<b>estuve</b>：強変化動詞。語尾 -e にはアクセント記号が付かない。'],
    ['¿Dónde [[estuviste|estar（tú）]] ayer?',
     '昨日はどこにいたの？',
     '<b>estuviste</b>：語根 estuv- ＋ -iste。'],
    ['Ayer [[tuve|tener（yo）]] que trabajar hasta tarde.',
     '昨日は遅くまで働かなければならなかった。',
     '<b>tuve</b>：tener の語根は tuv-。tener que＋不定詞。'],
    ['Mis padres [[tuvieron|tener]] tres hijos.',
     '両親は3人の子どもをもうけた。',
     '<b>tuvieron</b>：強変化動詞の3人称複数は -ieron。'],
    ['¿Qué [[hiciste|hacer（tú）]] el fin de semana? — [[Hice|hacer（yo）]] muchas cosas.',
     '週末は何をしたの？ — いろいろしたよ。',
     '<b>hiciste / Hice</b>：hacer の語根は hic-。'],
    ['Mi hermano [[hizo|hacer]] la cena.',
     '兄（弟）が夕食を作った。',
     '<b>hizo</b>：3人称単数だけ c が z になる（hico では「イコ」と読めないため）。'],
    ['No [[pude|poder（yo）]] dormir anoche.',
     '昨夜は眠れなかった。',
     '<b>pude</b>：poder の語根は pud-。'],
    ['Ellos no [[pudieron|poder]] venir a la fiesta.',
     '彼らはパーティーに来られなかった。',
     '<b>pudieron</b>：pud- ＋ -ieron。'],
    ['¿Dónde [[pusiste|poner（tú）]] las llaves? — Las [[puse|poner（yo）]] en la mesa.',
     '鍵をどこに置いたの？ — テーブルの上に置いたよ。',
     '<b>pusiste / puse</b>：poner の語根は pus-。'],
    ['[[Supe|saber（yo）]] la verdad ayer.',
     '私は昨日真実を知った。',
     '<b>Supe</b>：saber の点過去は「（その時）知った」という意味になる。'],
    ['Mis amigos [[vinieron|venir]] a verme.',
     '友人たちが私に会いに来た。',
     '<b>vinieron</b>：venir の語根は vin-。'],
    ['Ana no [[vino|venir]] a clase ayer.',
     'アナは昨日授業に来なかった。',
     '<b>vino</b>：3人称単数は -o（アクセント記号なし）。'],
    ['[[Quise|querer（yo）]] llamarte, pero no [[pude|poder（yo）]].',
     '君に電話しようとしたけど、できなかった。',
     '<b>Quise</b>：querer の語根は quis-。<b>pude</b>：poder。'],
    ['¿Qué te [[dijeron|decir]] tus padres?',
     'ご両親は君に何て言ったの？',
     '<b>dijeron</b>：j で終わる語根（dij-）では3人称複数が -eron（×dijieron）。'],
    ['Yo no [[dije|decir（yo）]] nada.',
     '私は何も言わなかった。',
     '<b>dije</b>：decir の語根は dij-。'],
    ['¿Quién [[trajo|traer]] este pastel?',
     '誰がこのケーキを持ってきたの？',
     '<b>trajo</b>：traer の語根は traj-。'],
    ['Mis amigos [[trajeron|traer]] vino a la fiesta.',
     '友人たちがパーティーにワインを持ってきた。',
     '<b>trajeron</b>：j の語根なので -eron。'],
    ['Yo [[conduje|conducir（yo）]] toda la noche.',
     '私は一晩中運転した。',
     '<b>conduje</b>：-ducir 動詞の語根は -duj-。'],
    ['Anoche [[hubo|haber]] un concierto en el parque.',
     '昨夜、公園でコンサートがあった。',
     '<b>hubo</b>：hay の点過去。今日では3人称単数 hubo だけを使う。'],
    ['Nosotros [[anduvimos|andar（nosotros）]] por la playa.',
     '私たちは浜辺を歩いた。',
     '<b>anduvimos</b>：andar は -ar 動詞だが強変化（anduv-）。'],
    ['Los libros no [[cupieron|caber]] en la caja.',
     '本は箱に入りきらなかった。',
     '<b>cupieron</b>：caber の語根は cup-。'],
    ['Mi madre se [[puso|ponerse]] muy contenta con el regalo.',
     '母はプレゼントをとても喜んだ。',
     '<b>puso</b>：ponerse＋形容詞「〜になる」の点過去。'],
    ['Vosotros [[estuvisteis|estar（vosotros）]] en casa todo el día.',
     '君たちは一日中家にいた。',
     '<b>estuvisteis</b>：estuv- ＋ -isteis。'],
    ['¿[[Tuviste|tener（tú）]] un buen viaje?',
     'いい旅だった？',
     '<b>Tuviste</b>：tuv- ＋ -iste。'],
    ['Ellos [[hicieron|hacer]] un pastel para mí.',
     '彼らは私のためにケーキを作ってくれた。',
     '<b>hicieron</b>：3人称複数は c のまま（hiz- にはならない）。'],
  ]},

  { num: '⑤', title: '不規則④⑤　yo 形の綴り・dar / ser / ir / ver', items: [
    ['Ayer [[llegué|llegar（yo）]] tarde a clase.',
     '昨日、私は授業に遅刻した。',
     '<b>llegué</b>：g の音を保つため、e の前で gu になる。'],
    ['[[Pagué|pagar（yo）]] la cuenta.',
     '私が会計を払った。',
     '<b>Pagué</b>：pagar も yo 形で g → gu。'],
    ['[[Busqué|buscar（yo）]] mis gafas por toda la casa.',
     '私は家中で眼鏡を探した。',
     '<b>Busqué</b>：k の音を保つため、e の前で c → qu。'],
    ['[[Jugué|jugar（yo）]] al tenis con mi hermano.',
     '私は兄（弟）とテニスをした。',
     '<b>Jugué</b>：jugar は点過去では語根変化せず、yo 形で g → gu だけ。'],
    ['[[Crucé|cruzar（yo）]] la calle sin mirar.',
     '私は見ないで通りを渡った。',
     '<b>Crucé</b>：e の前では z ではなく c と書く。'],
    ['[[Empecé|empezar（yo）]] a estudiar español el año pasado.',
     '私は去年スペイン語の勉強を始めた。',
     '<b>Empecé</b>：empezar も yo 形で z → c。3人称は empezó。'],
    ['¿Qué te [[dio|dar]] tu novio para tu cumpleaños?',
     '彼氏は誕生日に何をくれたの？',
     '<b>dio</b>：dar は -er/-ir 型の語尾をとる。1音節なのでアクセント記号なし。'],
    ['Le [[di|dar（yo）]] un regalo a mi madre.',
     '私は母にプレゼントをあげた。',
     '<b>di</b>：dar の yo 形。アクセント記号なし。'],
    ['¿[[Fuiste|ir（tú）]] al médico? — Sí, [[fui|ir（yo）]] ayer.',
     '医者に行った？ — うん、昨日行ったよ。',
     '<b>Fuiste / fui</b>：ir の点過去。行き先（al médico）があるので ir だとわかる。'],
    ['Cervantes [[fue|ser]] un gran escritor.',
     'セルバンテスは偉大な作家だった。',
     '<b>fue</b>：ser の点過去（ir と同じ形）。「作家だった」なので ser。'],
    ['Anoche [[vimos|ver（nosotros）]] una película muy buena.',
     '昨夜、私たちはとてもいい映画を見た。',
     '<b>vimos</b>：ver の点過去は vi, viste, vio, vimos, visteis, vieron。'],
    ['¿[[Viste|ver（tú）]] a María? — No, no la [[vi|ver（yo）]].',
     'マリアを見かけた？ — いや、見なかったよ。',
     '<b>Viste / vi</b>：ver の点過去。vi・vio にはアクセント記号が付かない。'],
  ]},

  { num: '⑥', title: '総合（複数の文法の組み合わせ）', items: [
    ['Ayer [[fui|ir（yo）]] al mercado, [[compré|comprar（yo）]] fruta y [[volví|volver（yo）]] a casa.',
     '昨日、市場に行って果物を買い、家に帰った。',
     '<b>fui</b>：ir。<b>compré</b>：-ar の yo 形。<b>volví</b>：-er の yo 形。一連の完結した出来事は点過去。'],
    ['Cuando [[oyó|oír]] la noticia, mi abuela [[se puso|ponerse]] muy triste.',
     'その知らせを聞いて、祖母はとても悲しんだ。',
     '<b>oyó</b>：-yó 型。<b>se puso</b>：ponerse＋形容詞の点過去。'],
    ['Anoche [[hubo|haber]] una fiesta, pero yo no [[pude|poder]] ir porque [[tuve|tener]] que trabajar.',
     '昨夜パーティーがあったが、私は仕事をしなければならなかったので行けなかった。',
     '<b>hubo</b>：hay の点過去。<b>pude / tuve</b>：強変化動詞の yo 形。'],
    ['¿Qué [[hicisteis|hacer（vosotros）]] ayer? — [[Fuimos|ir（nosotros）]] a la playa y [[jugamos|jugar（nosotros）]] al voleibol.',
     '君たち昨日は何をしたの？ — 海に行ってバレーボールをしたよ。',
     '<b>hicisteis</b>：hic- ＋ -isteis。<b>Fuimos</b>：ir。<b>jugamos</b>：nosotros 形は綴りの変化なし。'],
    ['El camarero nos [[trajo|traer]] la carta y [[pedimos|pedir（nosotros）]] paella.',
     'ウェイターがメニューを持ってきて、私たちはパエリアを頼んだ。',
     '<b>trajo</b>：強変化（traj-）。<b>pedimos</b>：nosotros 形は語根変化しない。'],
    ['Mi hermano [[leyó|leer]] la novela y le [[gustó|gustar]] mucho.',
     '兄（弟）はその小説を読んで、とても気に入った。',
     '<b>leyó</b>：-yó 型。<b>gustó</b>：主語 la novela（単数）。'],
    ['Los niños [[durmieron|dormir]] muy bien porque [[anduvieron|andar]] mucho.',
     '子どもたちはたくさん歩いたので、とてもよく眠った。',
     '<b>durmieron</b>：o → u。<b>anduvieron</b>：強変化（anduv-）。'],
    ['[[Llegué|llegar（yo）]] tarde y [[perdí|perder（yo）]] el tren.',
     '遅れて着いて、電車に乗り遅れた。',
     '<b>Llegué</b>：g → gu。<b>perdí</b>：perder は点過去では規則どおり。'],
    ['¿Quién te [[dijo|decir]] eso? — Me lo [[dijo|decir]] Carmen.',
     '誰がそれを言ったの？ — カルメンが教えてくれたんだ。',
     '<b>dijo</b>：decir の3人称単数（強変化）。me lo：間接→直接の順。'],
    ['En 1492 Colón [[llegó|llegar]] a América y [[descubrió|descubrir]] un nuevo mundo.',
     '1492年、コロンブスはアメリカに到達し、新しい世界を発見した。',
     '<b>llegó</b>：3人称単数は綴りの変化なし。<b>descubrió</b>：-ir 動詞の3人称単数。'],
  ]},
];

/* ── 問題データを、表示・復習で使う形（QUESTION_BANK と同じ形）に変換する ── */
function tanrenEscapeHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function tanrenSentenceHtml(src) {
  return src.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, function (_, answer, hint) {
    var html = '<span class="fillblank" onclick="toggleBlank(this)"><span class="fb-mask">______</span>' +
      '<span class="fb-answer">' + tanrenEscapeHtml(answer) + '</span></span>';
    if (hint) {
      html += '<span class="hintchip" onclick="toggleHintChip(this)"><span class="hc-q"></span>' +
        '<span class="hc-a">' + tanrenEscapeHtml(hint) + '</span></span>';
    }
    return html;
  });
}

const TANREN_BANK = [];
Object.keys(TANREN_SOURCE).forEach(function (lesson) {
  var n = 0;
  TANREN_SOURCE[lesson].forEach(function (group) {
    group.items.forEach(function (item) {
      n += 1;
      var answers = [];
      item[0].replace(/\[\[([^\]|]+)/g, function (_, a) { answers.push(a); });
      TANREN_BANK.push({
        id: 'L' + lesson + '-tr-' + n,
        lesson: Number(lesson),
        section_num: '鍛錬',
        section_title: group.num + ' ' + group.title,
        group_num: group.num,
        group_title: group.title,
        type: 'sentence',
        sentence_html: tanrenSentenceHtml(item[0]),
        ja: item[1],
        explanation_html: item[2],
        answers: answers
      });
    });
  });
});
