/* ============================================================
   tanren-bank.js
   各Lecciónの「鍛錬」タブの問題データ。
   レッスンページ（鍛錬タブの表示）と review.html（復習）の両方から読み込む。

   書き方：
     TANREN_SOURCE[課番号] = [ { num, title, items: [ [問題文, 和訳, 解説], ... ] }, ... ]
     問題文の [[答え|ヒント]] が穴埋めになる（ヒントは省略可）。
     問題のIDは「L課-tr-通し番号」。既存の問題の順番を入れ替えると
     復習の記録とずれるため、問題を追加するときは各課の末尾（最後のグループの後ろ）に足す。
   ============================================================ */

const TANREN_SOURCE = {};

TANREN_SOURCE[2] = [
  { num: '①', title: '名詞の性と数・冠詞', items: [
    ['Hoy es [[un|día の性に注意]] día muy bonito.',
     '今日はとてもいい日だ。',
     '<b>un</b>：día は語尾が -a だが<b>男性名詞</b>の例外。不定冠詞は男性単数の un。'],
    ['[[El|-ma で終わる名詞]] problema es muy difícil.',
     'その問題はとても難しい。',
     '<b>El</b>：語尾が -ma の名詞は多くが男性名詞（problema, idioma など）。'],
    ['[[La|mano の性に注意]] mano de mi hijo es muy [[pequeña|pequeño を一致させる]].',
     '私の息子の手はとても小さい。',
     '<b>La</b>：mano は語尾が -o だが<b>女性名詞</b>の例外。<b>pequeña</b>：形容詞も女性形にそろえる。'],
    ['Hay [[unas|不定冠詞・複数]] fotos de mi familia en la mesa.',
     'テーブルの上に家族の写真が何枚かある。',
     '<b>unas</b>：foto は fotografía の省略形なので<b>女性名詞</b>。女性複数の不定冠詞は unas。'],
    ['[[El|agua の冠詞に注意]] agua del río está muy [[fría|frío を一致させる]].',
     'その川の水はとても冷たい。',
     '<b>El</b>：agua は女性名詞だが、アクセントのある a- で始まるため単数では el を使う。<b>fría</b>：名詞自体は女性なので、形容詞は女性形。'],
    ['En la mesa hay tres [[lápices|lápiz の複数形]].',
     'テーブルの上に鉛筆が3本ある。',
     '<b>lápices</b>：-z で終わる名詞は z を c に変えて -es を付ける（lápiz → lápices）。'],
    ['En mi ciudad hay dos [[estaciones|estación の複数形]].',
     '私の町には駅が2つある。',
     '<b>estaciones</b>：子音で終わるので +es。複数形では強勢の位置が規則どおりになるため、アクセント記号が消える（estación → estaciones）。'],
    ['Hay dos [[paraguas|paraguas の複数形]] en la entrada.',
     '入口に傘が2本ある。',
     '<b>paraguas</b>：単数と複数で形が変わらない「単複同形の名詞」。数は冠詞や数詞で判断する。'],
    ['Es el coche [[del|de ＋ el]] padre de Ana.',
     'それはアナのお父さんの車だ。',
     '<b>del</b>：前置詞 de と定冠詞 el が続くと必ず縮約して del になる。'],
    ['Voy [[al|a ＋ el]] cine con [[la|hermana は女性名詞]] hermana de Pedro.',
     '私はペドロの姉（妹）と映画館へ行く。',
     '<b>al</b>：a ＋ el は縮約して al。<b>la</b>：hermana は女性名詞なので la。'],
    ['El libro es [[de él|前置詞 de ＋ 代名詞「彼」]], no [[del|前置詞 de ＋ 定冠詞 el]] profesor.',
     'その本は彼のもので、先生のものではない。',
     '<b>de él</b>：主語代名詞 él（アクセント記号あり）とは縮約しない。<b>del</b>：定冠詞 el（アクセント記号なし）とは縮約する。'],
    ['[[La|-ión で終わる名詞]] lección de hoy es muy interesante.',
     '今日の課はとても面白い。',
     '<b>La</b>：語尾が -ión の名詞は女性名詞（lección, nación など）。'],
    ['Tu padre es [[una|persona の性に注意]] persona muy [[simpática|simpático を一致させる]].',
     '君のお父さんはとても感じのいい人だ。',
     '<b>una</b>：persona は指す相手が男性でも<b>女性名詞</b>。<b>simpática</b>：形容詞も persona に合わせて女性形。'],
    ['[[El|-pa で終わる名詞]] mapa de España está sobre la mesa.',
     'スペインの地図はテーブルの上にある。',
     '<b>El</b>：mapa は語尾が -a だが<b>男性名詞</b>の例外。'],
    ['[[La|女性の学生]] estudiante mexicana está en [[la|clase の性]] clase de español.',
     'そのメキシコ人の女子学生はスペイン語の授業に出ている。',
     '<b>La</b>：estudiante は「男女同形の名詞」。女性を指すときは la estudiante（形容詞も mexicana）。<b>la</b>：clase は語尾 -e だが女性名詞。'],
  ]},

  { num: '②', title: '主語人称代名詞・ser と estar', items: [
    ['Nosotros [[somos|ser・nosotros]] de Osaka, pero ahora [[estamos|estar・nosotros]] en Madrid.',
     '私たちは大阪出身だが、今はマドリードにいる。',
     '<b>somos</b>：出身は ser（ser de＋場所）。<b>estamos</b>：今いる場所（所在）は estar。'],
    ['¿[[Eres|ser・tú]] tú estudiante? — Sí, [[soy|ser・yo]] estudiante de español.',
     '君は学生？ — うん、スペイン語の学生だよ。',
     '<b>Eres / soy</b>：身分・職業は ser。tú → eres、yo → soy。'],
    ['Mi padre [[es|職業]] médico y ahora [[está|所在]] en el hospital.',
     '私の父は医者で、今は病院にいる。',
     '<b>es</b>：職業（名詞）は ser。「estar＋名詞」という形はない。<b>está</b>：人の所在は estar。'],
    ['¿Cómo [[están|estar・ustedes]] ustedes? — [[Estamos|estar・nosotros]] muy bien, gracias.',
     '皆さんお元気ですか？ — とても元気です、ありがとう。',
     '<b>están</b>：ustedes は文法上3人称複数なので están。<b>Estamos</b>：体調・調子は estar。'],
    ['La fiesta [[es|イベントの開催場所]] en casa de Ana, pero Ana todavía [[está|人の所在]] en la universidad.',
     'パーティーはアナの家で開かれるが、アナはまだ大学にいる。',
     '<b>es</b>：イベントが「行われる」場所は ser。<b>está</b>：人や物が「いる・ある」場所は estar。'],
    ['[[Son|時刻（3時）]] las tres y media.',
     '3時半だ。',
     '<b>Son</b>：時刻は ser。2時以降は las（複数）に合わせて son を使う。'],
    ['[[Es|時刻（1時）]] la una de la tarde.',
     '午後1時だ。',
     '<b>Es</b>：1時だけは la una（単数）なので es を使う。'],
    ['La mesa [[es|素材]] de madera y [[está|所在]] en la cocina.',
     'そのテーブルは木製で、台所にある。',
     '<b>es</b>：素材（ser de＋素材）は ser。<b>está</b>：物の所在は、動かない物でも estar。'],
    ['Pedro [[es|性格]] nervioso, pero hoy [[está|今日の状態]] muy tranquilo.',
     'ペドロは神経質な性格だが、今日はとても落ち着いている。',
     '<b>es</b>：生まれつきの性格は ser。<b>está</b>：「今日は」という一時的な状態は estar。'],
    ['Ana, [[estás|今日に限った様子]] muy guapa hoy.',
     'アナ、今日はとてもきれいだね。',
     '<b>estás</b>：「今日は（いつもと違って）」という一時的な評価は estar。Ana es guapa.（ser）なら「アナは美人だ（性質）」。'],
    ['La puerta [[está|状態]] abierta, pero las ventanas [[están|状態・複数]] cerradas.',
     'ドアは開いているが、窓は閉まっている。',
     '<b>está / están</b>：開いている・閉まっているは状態なので estar。主語の数（la puerta / las ventanas）に合わせる。'],
    ['Madrid [[es|首都（補語）]] la capital de España y [[está|所在]] en el centro del país.',
     'マドリードはスペインの首都で、国の中央にある。',
     '<b>es</b>：「〜は…である」と名詞でイコールを表すときは ser。<b>está</b>：地名の所在も estar。'],
    ['Mi hermano [[está|体調]] enfermo y [[está|所在]] en casa.',
     '私の兄（弟）は病気で、家にいる。',
     '<b>está</b>：体調（病気）も所在も estar。'],
    ['Señora López, ¿[[es|usted の活用]] usted de México?',
     'ロペスさん、あなたはメキシコ出身ですか？',
     '<b>es</b>：usted は「あなた」という意味だが、文法上は<b>3人称単数</b>扱い。'],
    ['Ustedes [[son|ustedes の活用]] profesores, ¿verdad?',
     'あなた方は先生ですよね？',
     '<b>son</b>：ustedes は文法上<b>3人称複数</b>扱い。'],
    ['[[Nosotras|私たち（女性のみ）]] somos hermanas.',
     '私たちは姉妹だ。',
     '<b>Nosotras</b>：全員が女性なら nosotras。男性が1人でも含まれれば nosotros。'],
    ['—¿Quién es Juan? —[[Él|彼]] es el hermano de María.',
     'フアンって誰？ — マリアの兄（弟）だよ。',
     '<b>Él</b>：「彼」はアクセント記号付きの él。定冠詞 el と区別する。'],
    ['El libro [[es|所有]] de Ana, pero ahora [[está|所在]] en mi casa.',
     'その本はアナのものだが、今は私の家にある。',
     '<b>es</b>：所有（ser de＋人）は ser。<b>está</b>：今ある場所は estar。'],
    ['¿Dónde [[está|所在]] la estación? — [[Está|所在]] cerca de aquí.',
     '駅はどこにありますか？ — この近くにあります。',
     '<b>está</b>：特定の建物（la estación）の場所を尋ねる・答えるときは estar。'],
    ['Vosotros [[sois|ser・vosotros]] japoneses y [[estáis|estar・vosotros]] en España de vacaciones.',
     '君たちは日本人で、休暇でスペインに来ている。',
     '<b>sois</b>：国籍は ser。<b>estáis</b>：今いる場所は estar。どちらも vosotros の形（スペインで使う）。'],
  ]},

  { num: '③', title: 'さまざまな前置詞', items: [
    ['Un café [[sin|〜なしの]] azúcar y un té [[con|〜入りの]] leche, por favor.',
     '砂糖なしのコーヒーとミルクティーをください。',
     '<b>sin</b>：「〜なしで」。<b>con</b>：「〜と一緒に・〜入りの」。'],
    ['Estudio [[para|目的]] el examen de mañana.',
     '明日の試験のために勉強している。',
     '<b>para</b>：目的（〜に向けて）。por は原因・理由なので使わない。'],
    ['Gracias [[por|理由]] el regalo.',
     'プレゼントをありがとう。',
     '<b>por</b>：感謝の理由を表す。Gracias por ～ は決まった形。'],
    ['¿Vienes [[conmigo|con ＋ mí]] al cine? — No, voy [[con|〜と一緒に]] Juan.',
     '私と一緒に映画に行く？ — ううん、フアンと行くんだ。',
     '<b>conmigo</b>：con ＋ mí は特別な形 conmigo になる。<b>con</b>：3人称や名前の前ではそのまま con。'],
    ['Mañana estoy [[contigo|con ＋ ti]] todo el día.',
     '明日は一日中君と一緒にいるよ。',
     '<b>contigo</b>：con ＋ ti は特別な形 contigo になる。'],
    ['Es un libro [[sobre|〜について]] la historia de México.',
     'それはメキシコの歴史についての本だ。',
     '<b>sobre</b>：「〜の上に」のほか、「〜について」という意味もある。'],
    ['La biblioteca está abierta [[desde|起点]] las nueve [[hasta|終点]] las ocho.',
     '図書館は9時から8時まで開いている。',
     '<b>desde</b>：時間の起点「〜から」。<b>hasta</b>：終点「〜まで」。セットでよく使う。'],
    ['Estoy en Japón [[desde|起点]] abril.',
     '私は4月から日本にいる。',
     '<b>desde</b>：「（ある時点）から今まで」の起点を表す。'],
    ['Soy [[de|出身]] Kioto, pero vivo [[en|場所]] Osaka.',
     '私は京都出身だが、大阪に住んでいる。',
     '<b>de</b>：出身「〜の出身」。<b>en</b>：住んでいる場所「〜に」。'],
    ['Voy [[a|方向]] la universidad [[en|乗り物]] tren.',
     '私は電車で大学へ行く。',
     '<b>a</b>：行き先「〜へ」。<b>en</b>：乗り物で移動するときは en（en tren, en autobús）。'],
    ['El tren va [[de|出発点]] Madrid [[a|到着点]] Barcelona.',
     'その電車はマドリードからバルセロナへ行く。',
     '<b>de … a …</b>：「〜から…へ」。移動の出発点と到着点をセットで表す。'],
    ['Hoy no hay clase [[por|原因]] la lluvia.',
     '雨のせいで今日は授業がない。',
     '<b>por</b>：原因・理由「〜のせいで」。目的の para とは使い分ける。'],
    ['Esta tarde voy [[al|a ＋ el]] museo y después [[a|方向]] la casa [[de|所有]] Carmen.',
     '今日の午後は美術館へ行き、そのあとカルメンの家へ行く。',
     '<b>al</b>：a ＋ el museo → al museo。<b>a</b>：la casa は女性名詞なので縮約しない。<b>de</b>：所有「〜の」。'],
  ]},

  { num: '④', title: '形容詞と性数変化', items: [
    ['Mis padres son [[japoneses|japonés の男性複数]] y mi abuela es [[española|español の女性形]].',
     '私の両親は日本人で、祖母はスペイン人だ。',
     '<b>japoneses</b>：japonés ＋ es。複数ではアクセント記号が消える。<b>española</b>：子音で終わる国籍形容詞は女性形で ＋a。'],
    ['Laura es [[alemana|alemán の女性形]] y sus hermanos también son [[alemanes|alemán の男性複数]].',
     'ラウラはドイツ人で、彼女の兄弟たちもドイツ人だ。',
     '<b>alemana / alemanes</b>：alemán に -a / -es を付けると、アクセント記号が消える。'],
    ['Las chicas [[inglesas|inglés の女性複数]] son muy [[simpáticas|simpático を一致させる]].',
     'そのイギリス人の女の子たちはとても感じがいい。',
     '<b>inglesas</b>：inglés → inglesa → inglesas。<b>simpáticas</b>：女性複数に一致。'],
    ['Es una ciudad [[grande|名詞の後ろ]] y muy [[bonita|bonito を一致させる]].',
     'そこは大きくてとてもきれいな都市だ。',
     '<b>grande</b>：-e で終わる形容詞は性変化しない。名詞の後ろなので短縮もしない。<b>bonita</b>：ciudad（女性）に一致。'],
    ['Carlos es un [[buen|bueno：男性単数名詞の前]] amigo y Marta es una [[buena|bueno：女性単数名詞の前]] amiga.',
     'カルロスはいい友人で、マルタもいい友人だ。',
     '<b>buen</b>：男性単数名詞の直前では bueno → buen。<b>buena</b>：女性名詞の前では短縮しない。'],
    ['Hoy es un [[mal|malo：男性単数名詞の前]] día para ir a la playa.',
     '今日は海に行くには悪い日だ。',
     '<b>mal</b>：男性単数名詞（día）の直前では malo → mal。'],
    ['Picasso es un [[gran|grande：単数名詞の前]] pintor.',
     'ピカソは偉大な画家だ。',
     '<b>gran</b>：単数名詞の直前では grande → gran になり、「偉大な」という意味になる。'],
    ['Buenos Aires es una [[gran|grande：女性単数名詞の前]] ciudad.',
     'ブエノスアイレスはすばらしい都市だ。',
     '<b>gran</b>：grande は男性・女性どちらの<b>単数名詞</b>の前でも gran になる（buen・mal は男性単数の前だけ）。複数の前では grandes。'],
    ['Mis hermanos son [[trabajadores|trabajador の男性複数]], pero mi hermana es un poco [[holgazana|holgazán の女性形]].',
     '私の兄弟たちは勤勉だが、妹は少し怠け者だ。',
     '<b>trabajadores</b>：-dor で終わる形容詞の男性複数は ＋es。<b>holgazana</b>：-án で終わる形容詞の女性形は -ana（アクセント記号は消える）。'],
    ['Los estudiantes son [[jóvenes|joven の複数形]] e [[inteligentes|inteligente の複数形]].',
     '学生たちは若くて頭がいい。',
     '<b>jóvenes</b>：joven ＋ es。強勢の位置を保つため、複数形では<b>アクセント記号が付く</b>。<b>inteligentes</b>：-e で終わるので ＋s。※ i- で始まる語の前では y が e になる。'],
    ['Los coches [[azules|azul の複数形]] son muy [[caros|caro を一致させる]].',
     'その青い車（複数）はとても高い。',
     '<b>azules</b>：子音で終わる形容詞は性変化せず、複数で ＋es。<b>caros</b>：男性複数に一致。'],
    ['Hay [[muchos|数量を表す形容詞]] estudiantes [[chinos|chino を一致させる]] en mi universidad.',
     '私の大学には中国人の学生がたくさんいる。',
     '<b>muchos</b>：数量を表す形容詞は名詞の前に置き、性数一致する。<b>chinos</b>：国籍形容詞は名詞の後ろ。'],
    ['Hoy es el [[primer|primero：男性単数名詞の前]] día de clase.',
     '今日は授業の初日だ。',
     '<b>primer</b>：序数 primero も、bueno と同じく男性単数名詞の直前で -o が落ちる（el primer día / la primera clase）。'],
    ['Hay [[pocas|数量を表す形容詞]] personas en la calle.',
     '通りには人が少ない。',
     '<b>pocas</b>：persona は女性名詞なので poco → pocas（女性複数）。'],
    ['Las casas de la calle son [[viejas|viejo を一致させる]] pero muy [[bonitas|bonito を一致させる]].',
     'その通りの家々は古いが、とてもきれいだ。',
     '<b>viejas / bonitas</b>：主語 las casas（女性複数）に一致させる。ser の後ろの形容詞も性数一致する。'],
  ]},

  { num: '⑤', title: '所有形容詞・haber（hay）', items: [
    ['[[Mis|私の（複数）]] hermanos están en Barcelona y [[mi|私の（単数）]] hermana está en Tokio.',
     '私の兄弟たちはバルセロナに、姉（妹）は東京にいる。',
     '<b>Mis / mi</b>：mi は性変化せず、名詞の数だけに合わせる。'],
    ['[[Nuestros|私たちの（男性複数）]] padres son de Chile.',
     '私たちの両親はチリ出身だ。',
     '<b>Nuestros</b>：nuestro は被所有物（padres：男性複数）の性数に一致する。'],
    ['¿Es [[vuestra|君たちの（女性単数）]] casa? — Sí, es [[nuestra|私たちの（女性単数）]] casa.',
     'これは君たちの家？ — うん、私たちの家だよ。',
     '<b>vuestra / nuestra</b>：vuestro・nuestro は被所有物 casa（女性単数）に一致する。所有者の性ではない。'],
    ['Señor García, ¿es [[su|usted の所有形容詞]] coche?',
     'ガルシアさん、これはあなたの車ですか？',
     '<b>su</b>：usted（あなた）の所有形容詞は su。彼・彼女・彼らと同じ形。'],
    ['Ana y su hermano están con [[sus|彼らの（複数）]] padres.',
     'アナと弟は両親と一緒にいる。',
     '<b>sus</b>：被所有物 padres が複数なので su → sus。'],
    ['—¿De quién es la maleta? —Es [[mía|私の（後置形）]].',
     'そのスーツケースは誰の？ — 私のです。',
     '<b>mía</b>：ser の後ろでは後置形を使う。maleta（女性単数）に一致して mía。'],
    ['Los libros no son [[míos|私の（後置形）]], son [[tuyos|君の（後置形）]].',
     'その本は私のではなく、君のだ。',
     '<b>míos / tuyos</b>：後置形は被所有物 libros（男性複数）に完全に一致する。'],
    ['Una amiga [[mía|私の（後置形）]] es profesora de inglés.',
     '私の友人の一人は英語の先生だ。',
     '<b>mía</b>：「un/una＋名詞＋後置形」で「私の〜のうちの一人」。amiga（女性単数）に一致。'],
    ['Las llaves son [[suyas|彼の（後置形）]].',
     'その鍵は彼のものだ。',
     '<b>suyas</b>：所有者（彼）ではなく、被所有物 llaves（女性複数）に一致させる。'],
    ['[[Hay|存在]] un banco cerca de la estación.',
     '駅の近くに銀行が1つある。',
     '<b>Hay</b>：不特定のもの（un banco）が「ある」ことを表すのは hay。'],
    ['[[Hay|存在（複数）]] muchos turistas en Kioto.',
     '京都には観光客がたくさんいる。',
     '<b>Hay</b>：hay は後ろの名詞が複数でも形が変わらない。×Han とはしない。'],
    ['En la clase [[hay|存在]] veinte estudiantes, pero la profesora no [[está|特定の人の所在]].',
     '教室には学生が20人いるが、先生はいない。',
     '<b>hay</b>：数を示して存在を述べる。<b>está</b>：特定の人（la profesora）の所在は estar。'],
    ['—¿[[Hay|存在を尋ねる]] una farmacia por aquí? —Sí, [[la|特定のもの]] farmacia [[está|所在]] en la esquina.',
     'この辺に薬局はありますか？ — はい、薬局は角にあります。',
     '<b>Hay</b>：あるかどうか分からない不特定の薬局 → hay＋不定冠詞。<b>la / está</b>：話題になった特定の薬局 → 定冠詞＋estar。'],
    ['No [[hay|存在の否定]] leche en la nevera.',
     '冷蔵庫に牛乳がない。',
     '<b>hay</b>：否定文でも hay の形は同じ。no は動詞の直前に置く。'],
    ['[[Tu|君の（前置形）]] libro [[está|所在]] en la mesa, pero el [[mío|私のもの]] no.',
     '君の本はテーブルの上にあるが、私のはない。',
     '<b>Tu</b>：名詞の前は前置形。<b>está</b>：特定の本の所在。<b>mío</b>：「el＋後置形」で「私のもの」を表す（el mío＝el libro mío）。'],
  ]},

  { num: '⑥', title: '文の構造・否定文・疑問詞', items: [
    ['¿[[De dónde|出身を尋ねる]] eres? — Soy de Perú.',
     'どこの出身？ — ペルー出身だよ。',
     '<b>De dónde</b>：出身は ser de なので、疑問詞にも de を付ける。'],
    ['¿[[Con quién|誰と]] vives? — Vivo con mi familia.',
     '誰と住んでいるの？ — 家族と住んでいるよ。',
     '<b>Con quién</b>：前置詞は疑問詞の前に置く（×¿Quién vives con?）。'],
    ['¿[[De quién|所有者を尋ねる]] es el coche rojo?',
     'その赤い車は誰のもの？',
     '<b>De quién</b>：所有は ser de＋人なので、「誰の」は de quién。'],
    ['¿[[Cuál|範囲の決まった答え]] es tu número de teléfono?',
     '君の電話番号は？',
     '<b>Cuál</b>：答えの範囲が決まっているもの（番号・住所・名前など）は cuál で尋ねる。qué は使わない。'],
    ['¿[[Cuántas|数を尋ねる]] personas hay en tu familia?',
     '君の家族は何人？',
     '<b>Cuántas</b>：cuánto は後ろの名詞に性数一致する。personas（女性複数）→ cuántas。'],
    ['¿[[Qué|疑問形容詞]] hora es? — [[Son|時刻（5時）]] las cinco.',
     '何時？ — 5時だよ。',
     '<b>Qué</b>：「何の・どの」＋名詞は qué。<b>Son</b>：las cinco（複数）なので son。'],
    ['¿[[Cuándo|時を尋ねる]] es tu cumpleaños?',
     '君の誕生日はいつ？',
     '<b>Cuándo</b>：「いつ」。イベント・日付は ser を使う。'],
    ['¿[[Cómo|人柄・性質を尋ねる]] es tu profesor? — Es alto y muy simpático.',
     '君の先生はどんな人？ — 背が高くて、とても感じがいいよ。',
     '<b>Cómo</b>：¿Cómo es…? は性質（どんな人・物か）、¿Cómo está…? は状態（調子はどうか）を尋ねる。'],
    ['¿[[A dónde|行き先を尋ねる]] vas? — Voy [[al|a ＋ el]] supermercado.',
     'どこへ行くの？ — スーパーへ行くよ。',
     '<b>A dónde</b>：行き先「どこへ」。<b>al</b>：a ＋ el supermercado の縮約。'],
    ['—¿Estás cansado? —No, [[no|否定]] estoy cansado.',
     '疲れてる？ — いや、疲れてないよ。',
     '<b>no</b>：最初の No は「いいえ」、2つ目の no は動詞の直前に置く否定語。答えでは No, no… と2回続くことがよくある。'],
    ['¿[[Quiénes|誰（複数）]] son los chicos de la foto?',
     '写真の男の子たちは誰？',
     '<b>Quiénes</b>：尋ねる相手が複数（son los chicos）なので quiénes。'],
    ['¿[[Por qué|理由を尋ねる]] estás triste? — [[Porque|理由を答える]] mi perro está enfermo.',
     'どうして悲しいの？ — 犬が病気だからだよ。',
     '<b>Por qué</b>：理由を問う疑問詞（2語・アクセント記号あり）。<b>Porque</b>：理由を答える接続詞（1語・アクセント記号なし）。'],
  ]},

  { num: '⑦', title: '総合（複数の文法の組み合わせ）', items: [
    ['[[La|定冠詞]] capital de Argentina [[es|補語]] Buenos Aires y [[está|所在]] en el este del país.',
     'アルゼンチンの首都はブエノスアイレスで、国の東部にある。',
     '<b>La</b>：capital は女性名詞。<b>es</b>：「首都＝ブエノスアイレス」は ser。<b>está</b>：所在は estar。'],
    ['En [[nuestra|私たちの]] universidad [[hay|存在]] [[muchos|数量]] estudiantes [[extranjeros|extranjero を一致させる]].',
     '私たちの大学には留学生がたくさんいる。',
     '<b>nuestra</b>：universidad（女性）に一致。<b>hay</b>：存在。<b>muchos / extranjeros</b>：estudiantes（男性複数）に一致。'],
    ['¿[[Dónde|場所]] [[están|所在・複数]] [[mis|私の（複数）]] llaves? — [[Están|所在]] [[sobre|〜の上に]] la mesa.',
     '私の鍵はどこ？ — テーブルの上にあるよ。',
     '<b>Dónde</b>：場所。<b>están</b>：特定の物（mis llaves：複数）の所在。<b>mis</b>：複数形。<b>sobre</b>：「〜の上に」。'],
    ['María [[es|国籍]] [[mexicana|mexicano の女性形]], pero ahora [[está|所在]] en Japón [[por|理由]] su trabajo.',
     'マリアはメキシコ人だが、今は仕事の都合で日本にいる。',
     '<b>es</b>：国籍は ser。<b>mexicana</b>：女性形。<b>está</b>：今いる場所。<b>por</b>：理由「〜のために・〜の都合で」。'],
    ['[[El|agua の冠詞]] agua [[del|de ＋ el]] mar [[está|状態]] muy fría hoy.',
     '今日は海の水がとても冷たい。',
     '<b>El</b>：agua は女性名詞だが単数では el。<b>del</b>：de ＋ el mar。<b>está</b>：「今日は冷たい」は一時的な状態。'],
    ['Mi abuelo es un [[gran|grande の短縮形]] hombre, pero hoy [[está|今日の状態]] muy [[cansado|cansado を一致させる]].',
     '私の祖父は偉大な人だが、今日はとても疲れている。',
     '<b>gran</b>：単数名詞の前で「偉大な」。<b>está</b>：一時的な状態。<b>cansado</b>：abuelo（男性単数）に一致。'],
    ['—¿[[Cómo|調子を尋ねる]] estás? —[[Estoy|estar・yo]] bien, pero [[mi|私の]] madre [[está|体調]] [[enferma|enfermo を一致させる]].',
     '元気？ — 私は元気だけど、母が病気なんだ。',
     '<b>Cómo</b>：調子を尋ねる。<b>Estoy / está</b>：体調は estar。<b>mi</b>：単数。<b>enferma</b>：madre（女性）に一致。'],
    ['Los estudiantes [[de|所属]] la clase [[son|性格]] [[simpáticos|simpático を一致させる]] y [[trabajadores|trabajador を一致させる]].',
     'そのクラスの学生たちは感じがよくて勤勉だ。',
     '<b>de</b>：所属「〜の」。<b>son</b>：性格は ser。<b>simpáticos / trabajadores</b>：男性複数に一致（trabajador ＋ es）。'],
    ['—¿[[De quién|所有者を尋ねる]] son las gafas? —Son [[mías|私の（後置形）]].',
     'その眼鏡は誰の？ — 私のです。',
     '<b>De quién</b>：所有者。<b>mías</b>：gafas（眼鏡）は常に女性複数形で使う名詞なので mías。'],
    ['[[Hay|存在]] un restaurante [[italiano|国籍形容詞]] muy [[bueno|名詞の後ろ]] [[en|場所]] la calle Mayor.',
     'マヨール通りにとてもおいしいイタリア料理店がある。',
     '<b>Hay</b>：不特定の店の存在。<b>italiano</b>：国籍形容詞は後置。<b>bueno</b>：名詞の<b>後ろ</b>なので短縮しない（buen は名詞の直前だけ）。<b>en</b>：場所。'],
  ]},
];

/* ── 問題データを、表示・復習で使う形（QUESTION_BANK と同じ形）に変換する ── */
function tanrenEscapeHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function tanrenSentenceHtml(src) {
  return src.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, function (_, answer, hint) {
    var html = '<span class="fillblank" onclick="toggleBlank(this)"><span class="fb-mask">______</span>' +
      '<span class="fb-answer">' + tanrenEscapeHtml(answer) + '</span></span>';
    if (hint) {
      html += '<span class="hintchip" onclick="toggleHintChip(this)"><span class="hc-q"></span>' +
        '<span class="hc-a">' + tanrenEscapeHtml(hint) + '</span></span>';
    }
    return html;
  });
}

const TANREN_BANK = [];
Object.keys(TANREN_SOURCE).forEach(function (lesson) {
  var n = 0;
  TANREN_SOURCE[lesson].forEach(function (group) {
    group.items.forEach(function (item) {
      n += 1;
      var answers = [];
      item[0].replace(/\[\[([^\]|]+)/g, function (_, a) { answers.push(a); });
      TANREN_BANK.push({
        id: 'L' + lesson + '-tr-' + n,
        lesson: Number(lesson),
        section_num: '鍛錬',
        section_title: group.num + ' ' + group.title,
        group_num: group.num,
        group_title: group.title,
        type: 'sentence',
        sentence_html: tanrenSentenceHtml(item[0]),
        ja: item[1],
        explanation_html: item[2],
        answers: answers
      });
    });
  });
});
